<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Práctica 9. Reconstrucción filogenética</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="guion9_files/libs/clipboard/clipboard.min.js"></script>
<script src="guion9_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="guion9_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="guion9_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="guion9_files/libs/quarto-html/popper.min.js"></script>
<script src="guion9_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="guion9_files/libs/quarto-html/anchor.min.js"></script>
<link href="guion9_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="guion9_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="guion9_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="guion9_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="guion9_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Práctica 9. Reconstrucción filogenética</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">Introducción</h2>
<p>Aunque existen muy buenos programas para inferir filogenias fuera del entorno de R (es decir, para el terminal de Bash), utilizar las herramientas en R tiene la ventaja de poder representar los árboles, manipularlos y extraer información de ellos con toda la flexibilidad que permite un lenguaje de programación. Otros programas como RAxML o IQtree producirían los resultados en forma de archivos de texto con formato Newick o NEXUS. En R, los árboles serán objetos de clase <code>phylo</code>, que pueden también ser exportados como archivos de texto con formato Newick con la función <code>write.tree()</code> del paquete ape. Este paquete será cargado automáticamente cuando carguemos el paquete <code>phangorn</code>, que proporciona las principales funciones para inferencia filogenética.</p>
</section>
<section id="objetivos" class="level2">
<h2 class="anchored" data-anchor-id="objetivos">Objetivos</h2>
<p>Obtener una filogenia calibrada de homininos y algunos primates, a partir de secuencias mitocondriales.</p>
</section>
<section id="datos" class="level2">
<h2 class="anchored" data-anchor-id="datos">Datos</h2>
<p>Pinchando aquí descargaréis un alineamiento en formato FASTA de 42 cromosomas mitocondriales completos de: un gorila, cuatro chimpancés, cuatro bonobos, un Homo heidelbergensis (de hace unos 400000 años), 4 humanos denisovanos (de hace entre 30000 y 110000 años), 19 humanos neandertales (de hace entre 30000 y 180000 años) y 9 humanos anatómicamente modernos (actuales). Encontréis también el archivo en el aula virtual, con el nombre <code>mtDNA.fasta</code>, por si el enlace no funciona.</p>
<p>Debes haber guardado el archivo <code>mtDNA.fasta</code> en la carpeta de datos.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(phangorn)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ape</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>mtdna <span class="ot">&lt;-</span> <span class="fu">read.phyDat</span>(<span class="st">'../../data/data_9/mtDNA.fasta.txt'</span>, <span class="at">format =</span> <span class="st">'fasta'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Después de ejecutar el bloque anterior, habrás cargado los datos en el objeto de clase <code>phyDat</code> llamado <code>mtdna</code>. Puedes usar la consola de R para echarle un vistazo, por ejemplo con la función <code>glance()</code> o incluso para generar una imagen del alineamiento con image(). Si tienes instalado el paquete <code>Biostrings</code> (de Bioconductor), puedes crear un objeto de classe <code>DNAStringSet</code> con <code>as.StringSet(mtDNA)</code>, al que se le pueden aplicar muchas otras funciones. Pero no es necesario.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ejercicio
</div>
</div>
<div class="callout-body-container callout-body">
<p>¿Puedes confirmar el número de secuencias? ¿Qué longitud tiene el alineamiento? ¿Qué función usarías para extraer los nombres de las secuencias?</p>
<p>para ver el número de secuencias, solo con ver <code>mtdna</code> nos debe salir.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>mtdna</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>42 sequences with 16603 character and 974 different site patterns.
The states are a c g t </code></pre>
</div>
</div>
<p>para extraer el nombre de las secuencias usadmos la función `names()``</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(mtdna)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "G.gorilla_D38114"            "P.troglodytes_JF727212"     
 [3] "P.troglodytes_JN191207"      "P.troglodytes_JF727168"     
 [5] "P.troglodytes_HM068590"      "P.paniscus_KX211934"        
 [7] "P.paniscus_KX211928"         "P.paniscus_GU189658"        
 [9] "P.paniscus_GU189664"         "H.heidelbergensis_NC_023100"
[11] "H.s.denisova_NC_013993"      "H.s.denisova_FR695060"      
[13] "H.s.denisova_KX663333"       "H.s.denisova_KT780370"      
[15] "H.s.neandertal_KX198085"     "H.s.neandertal_KX198086"    
[17] "H.s.neandertal_MG025538"     "H.s.neandertal_NC_011137"   
[19] "H.s.neandertal_FM865409"     "H.s.neandertal_FM865407"    
[21] "H.s.neandertal_KX198088"     "H.s.neandertal_KX198083"    
[23] "H.s.neandertal_MG025540"     "H.s.neandertal_MG025536"    
[25] "H.s.neandertal_MG025537"     "H.s.neandertal_KX198087"    
[27] "H.s.neandertal_KX198082"     "H.s.neandertal_FM865408"    
[29] "H.s.neandertal_KU131206"     "H.s.neandertal_KF982693"    
[31] "H.s.neandertal_FM865411"     "H.s.neandertal_KY751400"    
[33] "H.s.neandertal_MK033602"     "H.s.modern_EU092846"        
[35] "H.s.modern_EU092665"         "H.s.modern_JQ045086"        
[37] "H.s.modern_DQ779927"         "H.s.modern_DQ779932"        
[39] "H.s.modern_AP008640"         "H.s.modern_AY495317"        
[41] "H.s.modern_J01415"           "H.s.modern_FJ236981"        </code></pre>
</div>
</div>
</div>
</div>
</section>
<section id="árboles-basados-en-distancias" class="level2">
<h2 class="anchored" data-anchor-id="árboles-basados-en-distancias">Árboles basados en distancias</h2>
<p>Los árboles NJ y UPGMA pueden proporcionar una idea rápida de cómo podría ser la relación filogenética entre las secuencias. Como métodos basados en distancias que son, necesitamos calcular primero las distancias. Podemos hacerlo en el mismo paso en el que generamos el árbol: <code>nj(dist.ml(mtdna))</code>. O bien, podemos hacerlo en dos pasos: guardar la matriz de distancias en un objeto de clase <code>dist</code>, y después generar los árboles.</p>
<p>La función <code>dist.ml()</code> (de <code>phangorn</code>) solo ofrece un par de modelos de evolución de nucleótidos para estimar distancias: F81 y JC69 (ofrece 17 modelos para proteínas). La función <code>dist.dna()</code> de <code>ape</code> (que no se aplica sobre objetos <code>phyDat</code>, sino <code>DNAbin</code>) ofrece algunas opciones más. Pero en el fondo, los métodos NJ y UPGMA son sólo heurísticos rápidos, con los que no hace falta usar distancias de alta precisión.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>distancias <span class="ot">&lt;-</span> <span class="fu">dist.ml</span>(mtdna, <span class="at">model =</span> <span class="st">'F81'</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>mt_nj    <span class="ot">&lt;-</span> <span class="fu">NJ</span>(distancias)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>mt_upgma <span class="ot">&lt;-</span> <span class="fu">upgma</span>(distancias)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ejercicio
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>¿De qué clase son los objetos <code>mt_nj</code> y <code>mt_upgma</code>?</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>mt_nj</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Phylogenetic tree with 42 tips and 40 internal nodes.

Tip labels:
  G.gorilla_D38114, P.troglodytes_JF727212, P.troglodytes_JN191207, P.troglodytes_JF727168, P.troglodytes_HM068590, P.paniscus_KX211934, ...

Unrooted; includes branch length(s).</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>mt_upgma</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Phylogenetic tree with 42 tips and 41 internal nodes.

Tip labels:
  G.gorilla_D38114, P.troglodytes_JF727212, P.troglodytes_JN191207, P.troglodytes_JF727168, P.troglodytes_HM068590, P.paniscus_KX211934, ...

Rooted; includes branch length(s).</code></pre>
</div>
</div>
<p>son árboles filogenéticos. - Consulta la estructura de estos objetos (<code>str(mt_nj)</code>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mt_nj)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 4
 $ edge       : int [1:81, 1:2] 44 44 54 54 53 53 52 52 51 51 ...
 $ edge.length: num [1:81] 1.97e-04 2.26e-04 -4.37e-08 4.37e-08 8.51e-08 ...
 $ tip.label  : chr [1:42] "G.gorilla_D38114" "P.troglodytes_JF727212" "P.troglodytes_JN191207" "P.troglodytes_JF727168" ...
 $ Nnode      : int 40
 - attr(*, "class")= chr "phylo"
 - attr(*, "order")= chr "postorder"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mt_upgma)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 4
 $ edge       : int [1:82, 1:2] 63 63 49 49 48 48 59 59 55 55 ...
 $ edge.length: num [1:82] 0.00127 0.00127 0.001422 0.000151 0.011063 ...
 $ tip.label  : chr [1:42] "G.gorilla_D38114" "P.troglodytes_JF727212" "P.troglodytes_JN191207" "P.troglodytes_JF727168" ...
 $ Nnode      : int 41
 - attr(*, "class")= chr "phylo"
 - attr(*, "order")= chr "postorder"</code></pre>
</div>
</div>
<ul>
<li>Represéntalos gráficamente (<code>plot(mt_nj)</code>) y consulta la ayuda de la función <code>plot.phylo()</code> para saber qué opciones de representación gráfica tienes.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mt_nj, <span class="at">main =</span> <span class="st">"árbon NJ"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">add.scale.bar</span>()</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">axisPhylo</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="guion9_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mt_upgma, <span class="at">main =</span> <span class="st">"árbol UPGMA"</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">add.scale.bar</span>()</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">axisPhylo</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="guion9_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Para qué sirven las funciones <code>add.scale.bar()</code> y <code>axisPhylo()</code>? la función <code>add.scale.bar()</code>sirve para añadir una barra de escala que indique la distancia genética, y <code>axisPhylo()</code> añade un eje temporal de distancia en la parte inferior del arbol.</li>
</ul>
</div>
</div>
</section>
<section id="enraizar" class="level1">
<h1>Enraizar</h1>
<section id="escogiendo-el-nodo" class="level2">
<h2 class="anchored" data-anchor-id="escogiendo-el-nodo">Escogiendo el nodo</h2>
<p>El árbol <code>mt_nj</code> no está enraizado (puedes comprobarlo con <code>is.rooted()</code>). Tenemos un par de opciones para enraizarlo. Una opción es <code>root()</code>, función en la que debemos especificar o bien el outgroup o bien el nodo interno en el que queremos situar la raíz. Para saber cómo identificar los nodos internos, puedes invocar <code>nodelabels()</code> después de haber usado <code>plot(mt_nj)</code>. Por ejemplo, en mi caso, el nodo 75 parece ser el ancestro entre gorilas y chimpancés, y por tanto también es ancestro de los humanos. Por tanto:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>mt_nj_rooted <span class="ot">&lt;-</span> <span class="fu">root</span>(mt_nj, <span class="at">node =</span> <span class="dv">75</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>mt_nj_rooted</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Phylogenetic tree with 42 tips and 40 internal nodes.

Tip labels:
  G.gorilla_D38114, P.troglodytes_JF727212, P.troglodytes_JN191207, P.troglodytes_JF727168, P.troglodytes_HM068590, P.paniscus_KX211934, ...

Unrooted; includes branch length(s).</code></pre>
</div>
</div>
</section>
<section id="con-un-outgroup" class="level2">
<h2 class="anchored" data-anchor-id="con-un-outgroup">Con un outgroup</h2>
<p>La numeración de los nodos internos siempre sigue a la de las hojas (o puntas) del árbol. El orden es caprichoso y después de enraizar, lo que era el 75 en mt_nj ahora será el 43 en mt_nj_rooted. Para garantizar que el enraizado no depende de la numeración, es más seguro usar el nombre del outgroup:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Debería dar el mismo resultado:</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>mt_nj_rooted <span class="ot">&lt;-</span> <span class="fu">root</span>(mt_nj, <span class="at">outgroup =</span> <span class="st">'G.gorilla_D38114'</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>mt_nj_rooted</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Phylogenetic tree with 42 tips and 40 internal nodes.

Tip labels:
  G.gorilla_D38114, P.troglodytes_JF727212, P.troglodytes_JN191207, P.troglodytes_JF727168, P.troglodytes_HM068590, P.paniscus_KX211934, ...

Unrooted; includes branch length(s).</code></pre>
</div>
</div>
</section>
<section id="en-el-punto-medio" class="level2">
<h2 class="anchored" data-anchor-id="en-el-punto-medio">En el punto medio</h2>
<p>Al representar el árbol enraizado (<code>plot(mt_nj_rooted</code>)) verás que no todas las hojas del árbol están a la misma altura. El punto exacto en el que se sitúa la raíz en una rama es arbitrario y <code>root()</code> no se esfuerza mucho en intentar que el árbol parezca ultramétrico. La otra opción es la función <code>midpoint()</code>, que escoge la posición de la raíz para que el árbol esté más equilibrado:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Esto sobreescribe el objeto anterior:</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>mt_nj_rooted <span class="ot">&lt;-</span> <span class="fu">midpoint</span>(mt_nj)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mt_nj_rooted, <span class="at">align.tip.label =</span> <span class="cn">TRUE</span>, <span class="at">main =</span> <span class="st">'NJ, enraizado en punto medio'</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nodelabels</span>(<span class="at">frame =</span> <span class="st">'none'</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">add.scale.bar</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="guion9_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="con-datación-de-hojas" class="level2">
<h2 class="anchored" data-anchor-id="con-datación-de-hojas">Con datación de hojas</h2>
<p>El enraizado en punto medio asume que todas las hojas son contemporáneas, como sucede en muchos casos. Pero, en nuestros datos tenemos secuencias contemporáneas y también arcaicas. En el apéndice encontrarás referencias sobre las edades estimadas de esas secuencias. Conociendo estas edades, podemos aplicar un método de enraizado llamado root-to-tip regression, mediante la función <code>rtt()</code> de <code>ape</code>.</p>
<p>Lo primero es crear un vector de fechas (o edades) para todas las hojas del árbol. Podemos expressar las edades de las secuencias arcaicas como el número (negativo) de años que hace que dejaron de evolucionar. Para saber el orden en que debemos especificar las edades, podemos usar <code>mt_nj\$tip.label</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>fechas <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>,</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>            <span class="sc">-</span><span class="dv">400000</span>,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>            <span class="sc">-</span><span class="dv">39000</span>, <span class="sc">-</span><span class="dv">50000</span>, <span class="sc">-</span><span class="dv">110000</span>, <span class="sc">-</span><span class="dv">110000</span>,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>            <span class="sc">-</span><span class="dv">39820</span>, <span class="sc">-</span><span class="dv">40096</span>, <span class="sc">-</span><span class="dv">38515</span>, <span class="sc">-</span><span class="dv">38310</span>, <span class="sc">-</span><span class="dv">39000</span>, <span class="sc">-</span><span class="dv">40000</span>, <span class="sc">-</span><span class="dv">41210</span>,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>            <span class="sc">-</span><span class="dv">42430</span>, <span class="sc">-</span><span class="dv">42540</span>, <span class="sc">-</span><span class="dv">43230</span>, <span class="sc">-</span><span class="dv">43780</span>, <span class="sc">-</span><span class="dv">44290</span>, <span class="sc">-</span><span class="dv">44770</span>, <span class="sc">-</span><span class="dv">49000</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>            <span class="sc">-</span><span class="dv">50000</span>, <span class="sc">-</span><span class="dv">82752</span>, <span class="sc">-</span><span class="dv">65000</span>, <span class="sc">-</span><span class="dv">122287</span>, <span class="sc">-</span><span class="dv">110450</span>,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>            <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Observa que hay que asignar el resultado de setNames() a "fechas"</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>fechas <span class="ot">&lt;-</span> <span class="fu">setNames</span>(fechas, mt_nj<span class="sc">$</span>tip.label)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>fechas</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           G.gorilla_D38114      P.troglodytes_JF727212 
                          0                           0 
     P.troglodytes_JN191207      P.troglodytes_JF727168 
                          0                           0 
     P.troglodytes_HM068590         P.paniscus_KX211934 
                          0                           0 
        P.paniscus_KX211928         P.paniscus_GU189658 
                          0                           0 
        P.paniscus_GU189664 H.heidelbergensis_NC_023100 
                          0                     -400000 
     H.s.denisova_NC_013993       H.s.denisova_FR695060 
                     -39000                      -50000 
      H.s.denisova_KX663333       H.s.denisova_KT780370 
                    -110000                     -110000 
    H.s.neandertal_KX198085     H.s.neandertal_KX198086 
                     -39820                      -40096 
    H.s.neandertal_MG025538    H.s.neandertal_NC_011137 
                     -38515                      -38310 
    H.s.neandertal_FM865409     H.s.neandertal_FM865407 
                     -39000                      -40000 
    H.s.neandertal_KX198088     H.s.neandertal_KX198083 
                     -41210                      -42430 
    H.s.neandertal_MG025540     H.s.neandertal_MG025536 
                     -42540                      -43230 
    H.s.neandertal_MG025537     H.s.neandertal_KX198087 
                     -43780                      -44290 
    H.s.neandertal_KX198082     H.s.neandertal_FM865408 
                     -44770                      -49000 
    H.s.neandertal_KU131206     H.s.neandertal_KF982693 
                     -50000                      -82752 
    H.s.neandertal_FM865411     H.s.neandertal_KY751400 
                     -65000                     -122287 
    H.s.neandertal_MK033602         H.s.modern_EU092846 
                    -110450                           0 
        H.s.modern_EU092665         H.s.modern_JQ045086 
                          0                           0 
        H.s.modern_DQ779927         H.s.modern_DQ779932 
                          0                           0 
        H.s.modern_AP008640         H.s.modern_AY495317 
                          0                           0 
          H.s.modern_J01415         H.s.modern_FJ236981 
                          0                           0 </code></pre>
</div>
</div>
<p>A continuación se escoge la posición de la raíz que optimiza la regresión entre distancia de raíz a puntas y edades de las puntas (Rambaut et al.&nbsp;2016).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>mt_nj_rtt <span class="ot">&lt;-</span> <span class="fu">rtt</span>(mt_nj, <span class="at">tip.dates =</span> fechas, <span class="at">objective =</span> <span class="st">'rms'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ejercicio
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>¿Se corresponden bien las distancias evolutivas estimadas con las dataciones?</li>
</ul>
<p>vamos a hacer una gráfica de este árbol y comparar la escala de distancia que sale de esta gráfica con el anterior:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mt_nj_rtt, <span class="at">main =</span> <span class="st">"árbol enraizado rtt"</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">axisPhylo</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="guion9_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>la distancia de este árbol y el anterior se parecen bastante, comparandolas con la misma escala</p>
<ul>
<li><p>¿Qué secuencias crees que se ajustan menos a su supuesta edad? como H.Heidelbergensis es el más antiguo debería de tener la raíz más corta y no la tiene, por lo que esa es la que menos se ajusta. luego, los neardentales no deberían estar todas a la misma altura porque se diferencian muchos años.</p></li>
<li><p>¿Qué razones puede haber para que la edad de una secuencia no se corresponda con la cantidad de cambios que ha acumulado? pueden haber variaciones en la tasa de mutación</p></li>
</ul>
</div>
</div>
</section>
</section>
<section id="distancias" class="level1">
<h1>Distancias</h1>
<p>Si has creado el objeto distancias antes, puedes usarlo para conocer la cantidad estimada de cambios entre los cromosomas mitocondriales humanos y de neandertales, por ejemplo. El objeto de clase dist es incómodo, pero podemos obtener una simple matriz fácilmente:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>distMat <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(distancias)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Aprovechando que los nombres de las secuencias tienen una estructura coherente, podemos usar startsWith() para seleccionar a los humanos modernos o a los neandertales, etc.:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Esto son vectores lógicos que podemos usar después para seleccionar filas</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="co"># y columnas de la matriz de distancias.</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>modernos     <span class="ot">&lt;-</span> <span class="fu">startsWith</span>(<span class="fu">colnames</span>(distMat), <span class="st">'H.s.modern'</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>neandertales <span class="ot">&lt;-</span> <span class="fu">startsWith</span>(<span class="fu">colnames</span>(distMat), <span class="st">'H.s.neandertal'</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>denisovanos  <span class="ot">&lt;-</span> <span class="fu">startsWith</span>(<span class="fu">colnames</span>(distMat), <span class="st">'H.s.denisova'</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>chimpances   <span class="ot">&lt;-</span> <span class="fu">startsWith</span>(<span class="fu">colnames</span>(distMat), <span class="st">'P.troglodytes'</span>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>bonobos      <span class="ot">&lt;-</span> <span class="fu">startsWith</span>(<span class="fu">colnames</span>(distMat), <span class="st">'P.paniscus'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>La distancia estimada media entre humanos y neandertales se puede obtener como:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(distMat[modernos, neandertales])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01214282</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ejercicio
</div>
</div>
<div class="callout-body-container callout-body">
<p>Calcula las distancias medias entre todos los grupos. ¿Cuántas veces mayor es la distancia entre humanos y chimpancés que entre humanos y neandertales? ¿Cómo calcularías la distancia media entre dos secuencias de humanos modernos?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(distMat[modernos, denisovanos])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02250501</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(distMat[modernos, chimpances])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09104153</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(distMat[modernos, bonobos])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09239182</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(distMat[neandertales, denisovanos])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02201398</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(distMat[neandertales, chimpances])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09041225</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(distMat[neandertales, bonobos])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09089352</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(distMat[denisovanos, chimpances])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09129525</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(distMat[denisovanos, bonobos])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09297814</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(distMat[chimpances, bonobos])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04059035</code></pre>
</div>
</div>
<p>la distancia entre humanos y chimpances es 0.09104153 y entre humanos y neandertales es 0.01214282, es 7,5 veces mayor.</p>
<p>para sacar la distancia ente dos humanos modernos:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>distMat[modernos, modernos]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    H.s.modern_EU092846 H.s.modern_EU092665 H.s.modern_JQ045086
H.s.modern_EU092846         0.000000000         0.004115877         0.005454272
H.s.modern_EU092665         0.004115877         0.000000000         0.005393179
H.s.modern_JQ045086         0.005454272         0.005393179         0.000000000
H.s.modern_DQ779927         0.005392590         0.005270729         0.004724566
H.s.modern_DQ779932         0.005513658         0.005391783         0.004906390
H.s.modern_AP008640         0.005517618         0.005152317         0.004787395
H.s.modern_AY495317         0.005635614         0.005148861         0.004784781
H.s.modern_J01415           0.005453806         0.005210372         0.004785411
H.s.modern_FJ236981         0.005331436         0.004966433         0.004481205
                    H.s.modern_DQ779927 H.s.modern_DQ779932 H.s.modern_AP008640
H.s.modern_EU092846         0.005392590         0.005513658         0.005517618
H.s.modern_EU092665         0.005270729         0.005391783         0.005152317
H.s.modern_JQ045086         0.004724566         0.004906390         0.004787395
H.s.modern_DQ779927         0.000000000         0.001087163         0.002359394
H.s.modern_DQ779932         0.001087163         0.000000000         0.002298600
H.s.modern_AP008640         0.002359394         0.002298600         0.000000000
H.s.modern_AY495317         0.002478978         0.002660427         0.001692960
H.s.modern_J01415           0.002418729         0.002600192         0.001693182
H.s.modern_FJ236981         0.002055212         0.002236605         0.001269395
                    H.s.modern_AY495317 H.s.modern_J01415 H.s.modern_FJ236981
H.s.modern_EU092846         0.005635614      0.0054538063        0.0053314359
H.s.modern_EU092665         0.005148861      0.0052103722        0.0049664328
H.s.modern_JQ045086         0.004784781      0.0047854113        0.0044812052
H.s.modern_DQ779927         0.002478978      0.0024187289        0.0020552122
H.s.modern_DQ779932         0.002660427      0.0026001920        0.0022366046
H.s.modern_AP008640         0.001692960      0.0016931824        0.0012693954
H.s.modern_AY495317         0.000000000      0.0010873068        0.0009058850
H.s.modern_J01415           0.001087307      0.0000000000        0.0006642889
H.s.modern_FJ236981         0.000905885      0.0006642889        0.0000000000</code></pre>
</div>
</div>
<p>asi se ven las secuencias entre todos los modernos entre ellos.</p>
</div>
</div>
<p>Las distancias estimadas no son exactas. Cuanto mayor es la distancia, mayor es el error en la estimación. Además el modelo disponible podia no ser el adecuado. Pero nos ayudan a estimar el tiempo transcurrido desde que dos linajes se separaron, si asumimos el reloj molecular. Por ejemplo, estas distancias sugieren que los humanos modernos divergieron de los neandertales hace una cantidad de tiempo aproximadamente igual al 13.3% del tiempo que nos separa de los chimpancés, que podrían ser más de 850000 años si del chimpancé nos separan 6.5 millones de años.</p>
<p>En los árboles las distancias se representan mediante la suma de las longitudes que separan las hojas. Las podemos obtener con la función <code>cophenetic()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>distCofen <span class="ot">&lt;-</span> <span class="fu">cophenetic</span>(mt_nj_rooted)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>distCofen</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            G.gorilla_D38114 P.troglodytes_JF727212
G.gorilla_D38114                   0.0000000             0.11466727
P.troglodytes_JF727212             0.1146673             0.00000000
P.troglodytes_JN191207             0.1111627             0.02174279
P.troglodytes_JF727168             0.1113715             0.02195160
P.troglodytes_HM068590             0.1117631             0.02234314
P.paniscus_KX211934                0.1130582             0.04239501
P.paniscus_KX211928                0.1138006             0.04313745
P.paniscus_GU189658                0.1125093             0.04184619
P.paniscus_GU189664                0.1130060             0.04234281
H.heidelbergensis_NC_023100        0.1126182             0.09008405
H.s.denisova_NC_013993             0.1181911             0.09565697
H.s.denisova_FR695060              0.1181905             0.09565638
H.s.denisova_KX663333              0.1161296             0.09359546
H.s.denisova_KT780370              0.1169174             0.09438324
H.s.neandertal_KX198085            0.1157351             0.09320092
H.s.neandertal_KX198086            0.1157352             0.09320100
H.s.neandertal_MG025538            0.1156743             0.09314018
H.s.neandertal_NC_011137           0.1155167             0.09298257
H.s.neandertal_FM865409            0.1154097             0.09287555
H.s.neandertal_FM865407            0.1153725             0.09283834
H.s.neandertal_KX198088            0.1153962             0.09286200
H.s.neandertal_KX198083            0.1153955             0.09286134
H.s.neandertal_MG025540            0.1157350             0.09320079
H.s.neandertal_MG025536            0.1160658             0.09353165
H.s.neandertal_MG025537            0.1154384             0.09290419
H.s.neandertal_KX198087            0.1153893             0.09285514
H.s.neandertal_KX198082            0.1151583             0.09262410
H.s.neandertal_FM865408            0.1153290             0.09279488
H.s.neandertal_KU131206            0.1146131             0.09207896
H.s.neandertal_KF982693            0.1148726             0.09233849
H.s.neandertal_FM865411            0.1148852             0.09235103
H.s.neandertal_KY751400            0.1155218             0.09298762
H.s.neandertal_MK033602            0.1149863             0.09245209
H.s.modern_EU092846                0.1162617             0.09372751
H.s.modern_EU092665                0.1155165             0.09298237
H.s.modern_JQ045086                0.1160105             0.09347635
H.s.modern_DQ779927                0.1156320             0.09309783
H.s.modern_DQ779932                0.1156431             0.09310898
H.s.modern_AP008640                0.1156449             0.09311074
H.s.modern_AY495317                0.1158780             0.09334387
H.s.modern_J01415                  0.1157700             0.09323589
H.s.modern_FJ236981                0.1153929             0.09285876
                            P.troglodytes_JN191207 P.troglodytes_JF727168
G.gorilla_D38114                       0.111162742            0.111371548
P.troglodytes_JF727212                 0.021742793            0.021951600
P.troglodytes_JN191207                 0.000000000            0.002526805
P.troglodytes_JF727168                 0.002526805            0.000000000
P.troglodytes_HM068590                 0.002918348            0.002782670
P.paniscus_KX211934                    0.038890484            0.039099290
P.paniscus_KX211928                    0.039632922            0.039841728
P.paniscus_GU189658                    0.038341663            0.038550470
P.paniscus_GU189664                    0.038838279            0.039047086
H.heidelbergensis_NC_023100            0.086579517            0.086788324
H.s.denisova_NC_013993                 0.092152439            0.092361246
H.s.denisova_FR695060                  0.092151853            0.092360660
H.s.denisova_KX663333                  0.090090928            0.090299735
H.s.denisova_KT780370                  0.090878707            0.091087513
H.s.neandertal_KX198085                0.089696386            0.089905192
H.s.neandertal_KX198086                0.089696473            0.089905280
H.s.neandertal_MG025538                0.089635645            0.089844451
H.s.neandertal_NC_011137               0.089478042            0.089686848
H.s.neandertal_FM865409                0.089371016            0.089579823
H.s.neandertal_FM865407                0.089333811            0.089542618
H.s.neandertal_KX198088                0.089357468            0.089566274
H.s.neandertal_KX198083                0.089356804            0.089565610
H.s.neandertal_MG025540                0.089696259            0.089905066
H.s.neandertal_MG025536                0.090027120            0.090235927
H.s.neandertal_MG025537                0.089399660            0.089608466
H.s.neandertal_KX198087                0.089350608            0.089559415
H.s.neandertal_KX198082                0.089119572            0.089328379
H.s.neandertal_FM865408                0.089290347            0.089499154
H.s.neandertal_KU131206                0.088574433            0.088783240
H.s.neandertal_KF982693                0.088833956            0.089042762
H.s.neandertal_FM865411                0.088846502            0.089055309
H.s.neandertal_KY751400                0.089483085            0.089691892
H.s.neandertal_MK033602                0.088947561            0.089156368
H.s.modern_EU092846                    0.090222979            0.090431785
H.s.modern_EU092665                    0.089477836            0.089686643
H.s.modern_JQ045086                    0.089971816            0.090180622
H.s.modern_DQ779927                    0.089593301            0.089802107
H.s.modern_DQ779932                    0.089604445            0.089813252
H.s.modern_AP008640                    0.089606206            0.089815012
H.s.modern_AY495317                    0.089839344            0.090048150
H.s.modern_J01415                      0.089731356            0.089940163
H.s.modern_FJ236981                    0.089354224            0.089563031
                            P.troglodytes_HM068590 P.paniscus_KX211934
G.gorilla_D38114                       0.111763091         0.113058155
P.troglodytes_JF727212                 0.022343142         0.042395015
P.troglodytes_JN191207                 0.002918348         0.038890484
P.troglodytes_JF727168                 0.002782670         0.039099290
P.troglodytes_HM068590                 0.000000000         0.039490833
P.paniscus_KX211934                    0.039490833         0.000000000
P.paniscus_KX211928                    0.040233271         0.009914495
P.paniscus_GU189658                    0.038942012         0.008623237
P.paniscus_GU189664                    0.039438628         0.009119853
H.heidelbergensis_NC_023100            0.087179867         0.088474930
H.s.denisova_NC_013993                 0.092752788         0.094047852
H.s.denisova_FR695060                  0.092752203         0.094047266
H.s.denisova_KX663333                  0.090691277         0.091986341
H.s.denisova_KT780370                  0.091479056         0.092774120
H.s.neandertal_KX198085                0.090296735         0.091591799
H.s.neandertal_KX198086                0.090296822         0.091591886
H.s.neandertal_MG025538                0.090235994         0.091531057
H.s.neandertal_NC_011137               0.090078391         0.091373455
H.s.neandertal_FM865409                0.089971365         0.091266429
H.s.neandertal_FM865407                0.089934160         0.091229224
H.s.neandertal_KX198088                0.089957817         0.091252880
H.s.neandertal_KX198083                0.089957153         0.091252217
H.s.neandertal_MG025540                0.090296608         0.091591672
H.s.neandertal_MG025536                0.090627469         0.091922533
H.s.neandertal_MG025537                0.090000009         0.091295072
H.s.neandertal_KX198087                0.089950957         0.091246021
H.s.neandertal_KX198082                0.089719921         0.091014985
H.s.neandertal_FM865408                0.089890696         0.091185760
H.s.neandertal_KU131206                0.089174782         0.090469846
H.s.neandertal_KF982693                0.089434305         0.090729369
H.s.neandertal_FM865411                0.089446851         0.090741915
H.s.neandertal_KY751400                0.090083434         0.091378498
H.s.neandertal_MK033602                0.089547910         0.090842974
H.s.modern_EU092846                    0.090823328         0.092118392
H.s.modern_EU092665                    0.090078185         0.091373249
H.s.modern_JQ045086                    0.090572165         0.091867229
H.s.modern_DQ779927                    0.090193650         0.091488713
H.s.modern_DQ779932                    0.090204794         0.091499858
H.s.modern_AP008640                    0.090206555         0.091501619
H.s.modern_AY495317                    0.090439693         0.091734757
H.s.modern_J01415                      0.090331705         0.091626769
H.s.modern_FJ236981                    0.089954573         0.091249637
                            P.paniscus_KX211928 P.paniscus_GU189658
G.gorilla_D38114                    0.113800593         0.112509334
P.troglodytes_JF727212              0.043137453         0.041846195
P.troglodytes_JN191207              0.039632922         0.038341663
P.troglodytes_JF727168              0.039841728         0.038550470
P.troglodytes_HM068590              0.040233271         0.038942012
P.paniscus_KX211934                 0.009914495         0.008623237
P.paniscus_KX211928                 0.000000000         0.004971332
P.paniscus_GU189658                 0.004971332         0.000000000
P.paniscus_GU189664                 0.004968024         0.004176689
H.heidelbergensis_NC_023100         0.089217369         0.087926110
H.s.denisova_NC_013993              0.094790290         0.093499032
H.s.denisova_FR695060               0.094789705         0.093498446
H.s.denisova_KX663333               0.092728780         0.091437521
H.s.denisova_KT780370               0.093516558         0.092225299
H.s.neandertal_KX198085             0.092334237         0.091042978
H.s.neandertal_KX198086             0.092334324         0.091043066
H.s.neandertal_MG025538             0.092273496         0.090982237
H.s.neandertal_NC_011137            0.092115893         0.090824635
H.s.neandertal_FM865409             0.092008867         0.090717609
H.s.neandertal_FM865407             0.091971662         0.090680404
H.s.neandertal_KX198088             0.091995319         0.090704060
H.s.neandertal_KX198083             0.091994655         0.090703396
H.s.neandertal_MG025540             0.092334110         0.091042852
H.s.neandertal_MG025536             0.092664971         0.091373713
H.s.neandertal_MG025537             0.092037511         0.090746252
H.s.neandertal_KX198087             0.091988459         0.090697201
H.s.neandertal_KX198082             0.091757423         0.090466165
H.s.neandertal_FM865408             0.091928199         0.090636940
H.s.neandertal_KU131206             0.091212284         0.089921026
H.s.neandertal_KF982693             0.091471807         0.090180548
H.s.neandertal_FM865411             0.091484353         0.090193095
H.s.neandertal_KY751400             0.092120936         0.090829678
H.s.neandertal_MK033602             0.091585412         0.090294154
H.s.modern_EU092846                 0.092860830         0.091569571
H.s.modern_EU092665                 0.092115688         0.090824429
H.s.modern_JQ045086                 0.092609667         0.091318409
H.s.modern_DQ779927                 0.092231152         0.090939893
H.s.modern_DQ779932                 0.092242296         0.090951038
H.s.modern_AP008640                 0.092244057         0.090952799
H.s.modern_AY495317                 0.092477195         0.091185936
H.s.modern_J01415                   0.092369207         0.091077949
H.s.modern_FJ236981                 0.091992075         0.090700817
                            P.paniscus_GU189664 H.heidelbergensis_NC_023100
G.gorilla_D38114                    0.113005950                  0.11261821
P.troglodytes_JF727212              0.042342810                  0.09008405
P.troglodytes_JN191207              0.038838279                  0.08657952
P.troglodytes_JF727168              0.039047086                  0.08678832
P.troglodytes_HM068590              0.039438628                  0.08717987
P.paniscus_KX211934                 0.009119853                  0.08847493
P.paniscus_KX211928                 0.004968024                  0.08921737
P.paniscus_GU189658                 0.004176689                  0.08792611
P.paniscus_GU189664                 0.000000000                  0.08842273
H.heidelbergensis_NC_023100         0.088422726                  0.00000000
H.s.denisova_NC_013993              0.093995647                  0.01324101
H.s.denisova_FR695060               0.093995062                  0.01324042
H.s.denisova_KX663333               0.091934137                  0.01117949
H.s.denisova_KT780370               0.092721915                  0.01196727
H.s.neandertal_KX198085             0.091539594                  0.01762539
H.s.neandertal_KX198086             0.091539681                  0.01762548
H.s.neandertal_MG025538             0.091478853                  0.01756465
H.s.neandertal_NC_011137            0.091321250                  0.01740705
H.s.neandertal_FM865409             0.091214224                  0.01730003
H.s.neandertal_FM865407             0.091177019                  0.01726282
H.s.neandertal_KX198088             0.091200676                  0.01728648
H.s.neandertal_KX198083             0.091200012                  0.01728581
H.s.neandertal_MG025540             0.091539468                  0.01762527
H.s.neandertal_MG025536             0.091870328                  0.01795613
H.s.neandertal_MG025537             0.091242868                  0.01732867
H.s.neandertal_KX198087             0.091193816                  0.01727962
H.s.neandertal_KX198082             0.090962781                  0.01704858
H.s.neandertal_FM865408             0.091133556                  0.01721936
H.s.neandertal_KU131206             0.090417641                  0.01650344
H.s.neandertal_KF982693             0.090677164                  0.01676296
H.s.neandertal_FM865411             0.090689711                  0.01677551
H.s.neandertal_KY751400             0.091326293                  0.01741209
H.s.neandertal_MK033602             0.090790769                  0.01687657
H.s.modern_EU092846                 0.092066187                  0.01815199
H.s.modern_EU092665                 0.091321045                  0.01740685
H.s.modern_JQ045086                 0.091815024                  0.01790082
H.s.modern_DQ779927                 0.091436509                  0.01752231
H.s.modern_DQ779932                 0.091447653                  0.01753345
H.s.modern_AP008640                 0.091449414                  0.01753521
H.s.modern_AY495317                 0.091682552                  0.01776835
H.s.modern_J01415                   0.091574565                  0.01766037
H.s.modern_FJ236981                 0.091197432                  0.01728323
                            H.s.denisova_NC_013993 H.s.denisova_FR695060
G.gorilla_D38114                      0.1181911311          0.1181905454
P.troglodytes_JF727212                0.0956569705          0.0956563848
P.troglodytes_JN191207                0.0921524392          0.0921518535
P.troglodytes_JF727168                0.0923612458          0.0923606601
P.troglodytes_HM068590                0.0927527883          0.0927522026
P.paniscus_KX211934                   0.0940478521          0.0940472664
P.paniscus_KX211928                   0.0947902903          0.0947897046
P.paniscus_GU189658                   0.0934990319          0.0934984462
P.paniscus_GU189664                   0.0939956475          0.0939950618
H.heidelbergensis_NC_023100           0.0132410053          0.0132404196
H.s.denisova_NC_013993                0.0000000000          0.0001206936
H.s.denisova_FR695060                 0.0001206936          0.0000000000
H.s.denisova_KX663333                 0.0044220467          0.0044214610
H.s.denisova_KT780370                 0.0052098250          0.0052092393
H.s.neandertal_KX198085               0.0231983163          0.0231977306
H.s.neandertal_KX198086               0.0231984036          0.0231978179
H.s.neandertal_MG025538               0.0231375750          0.0231369893
H.s.neandertal_NC_011137              0.0229799724          0.0229793866
H.s.neandertal_FM865409               0.0228729468          0.0228723610
H.s.neandertal_FM865407               0.0228357417          0.0228351559
H.s.neandertal_KX198088               0.0228593981          0.0228588124
H.s.neandertal_KX198083               0.0228587343          0.0228581486
H.s.neandertal_MG025540               0.0231981898          0.0231976041
H.s.neandertal_MG025536               0.0235290507          0.0235284650
H.s.neandertal_MG025537               0.0229015901          0.0229010044
H.s.neandertal_KX198087               0.0228525388          0.0228519530
H.s.neandertal_KX198082               0.0226215028          0.0226209171
H.s.neandertal_FM865408               0.0227922779          0.0227916922
H.s.neandertal_KU131206               0.0220763637          0.0220757780
H.s.neandertal_KF982693               0.0223358862          0.0223353005
H.s.neandertal_FM865411               0.0223484329          0.0223478471
H.s.neandertal_KY751400               0.0229850156          0.0229844299
H.s.neandertal_MK033602               0.0224494916          0.0224489059
H.s.modern_EU092846                   0.0237249092          0.0237243235
H.s.modern_EU092665                   0.0229797670          0.0229791813
H.s.modern_JQ045086                   0.0234737463          0.0234731606
H.s.modern_DQ779927                   0.0230952311          0.0230946454
H.s.modern_DQ779932                   0.0231063755          0.0231057897
H.s.modern_AP008640                   0.0231081364          0.0231075507
H.s.modern_AY495317                   0.0233412742          0.0233406885
H.s.modern_J01415                     0.0232332869          0.0232327012
H.s.modern_FJ236981                   0.0228561545          0.0228555688
                            H.s.denisova_KX663333 H.s.denisova_KT780370
G.gorilla_D38114                      0.116129620           0.116917399
P.troglodytes_JF727212                0.093595460           0.094383238
P.troglodytes_JN191207                0.090090928           0.090878707
P.troglodytes_JF727168                0.090299735           0.091087513
P.troglodytes_HM068590                0.090691277           0.091479056
P.paniscus_KX211934                   0.091986341           0.092774120
P.paniscus_KX211928                   0.092728780           0.093516558
P.paniscus_GU189658                   0.091437521           0.092225299
P.paniscus_GU189664                   0.091934137           0.092721915
H.heidelbergensis_NC_023100           0.011179495           0.011967273
H.s.denisova_NC_013993                0.004422047           0.005209825
H.s.denisova_FR695060                 0.004421461           0.005209239
H.s.denisova_KX663333                 0.000000000           0.002116938
H.s.denisova_KT780370                 0.002116938           0.000000000
H.s.neandertal_KX198085               0.021136806           0.021924584
H.s.neandertal_KX198086               0.021136893           0.021924671
H.s.neandertal_MG025538               0.021076064           0.021863843
H.s.neandertal_NC_011137              0.020918462           0.021706240
H.s.neandertal_FM865409               0.020811436           0.021599214
H.s.neandertal_FM865407               0.020774231           0.021562009
H.s.neandertal_KX198088               0.020797887           0.021585666
H.s.neandertal_KX198083               0.020797224           0.021585002
H.s.neandertal_MG025540               0.021136679           0.021924457
H.s.neandertal_MG025536               0.021467540           0.022255318
H.s.neandertal_MG025537               0.020840079           0.021627858
H.s.neandertal_KX198087               0.020791028           0.021578806
H.s.neandertal_KX198082               0.020559992           0.021347770
H.s.neandertal_FM865408               0.020730767           0.021518545
H.s.neandertal_KU131206               0.020014853           0.020802631
H.s.neandertal_KF982693               0.020274375           0.021062154
H.s.neandertal_FM865411               0.020286922           0.021074700
H.s.neandertal_KY751400               0.020923505           0.021711283
H.s.neandertal_MK033602               0.020387981           0.021175759
H.s.modern_EU092846                   0.021663398           0.022451177
H.s.modern_EU092665                   0.020918256           0.021706034
H.s.modern_JQ045086                   0.021412236           0.022200014
H.s.modern_DQ779927                   0.021033720           0.021821499
H.s.modern_DQ779932                   0.021044865           0.021832643
H.s.modern_AP008640                   0.021046626           0.021834404
H.s.modern_AY495317                   0.021279763           0.022067542
H.s.modern_J01415                     0.021171776           0.021959554
H.s.modern_FJ236981                   0.020794644           0.021582422
                            H.s.neandertal_KX198085 H.s.neandertal_KX198086
G.gorilla_D38114                       1.157351e-01            1.157352e-01
P.troglodytes_JF727212                 9.320092e-02            9.320100e-02
P.troglodytes_JN191207                 8.969639e-02            8.969647e-02
P.troglodytes_JF727168                 8.990519e-02            8.990528e-02
P.troglodytes_HM068590                 9.029673e-02            9.029682e-02
P.paniscus_KX211934                    9.159180e-02            9.159189e-02
P.paniscus_KX211928                    9.233424e-02            9.233432e-02
P.paniscus_GU189658                    9.104298e-02            9.104307e-02
P.paniscus_GU189664                    9.153959e-02            9.153968e-02
H.heidelbergensis_NC_023100            1.762539e-02            1.762548e-02
H.s.denisova_NC_013993                 2.319832e-02            2.319840e-02
H.s.denisova_FR695060                  2.319773e-02            2.319782e-02
H.s.denisova_KX663333                  2.113681e-02            2.113689e-02
H.s.denisova_KT780370                  2.192458e-02            2.192467e-02
H.s.neandertal_KX198085                0.000000e+00            0.000000e+00
H.s.neandertal_KX198086                0.000000e+00            0.000000e+00
H.s.neandertal_MG025538                6.040775e-05            6.049507e-05
H.s.neandertal_NC_011137               3.624617e-04            3.625490e-04
H.s.neandertal_FM865409                7.909519e-04            7.910392e-04
H.s.neandertal_FM865407                9.680519e-04            9.681392e-04
H.s.neandertal_KX198088                9.917084e-04            9.917957e-04
H.s.neandertal_KX198083                9.910446e-04            9.911319e-04
H.s.neandertal_MG025540               -4.365660e-08            4.365660e-08
H.s.neandertal_MG025536                2.748878e-03            2.748966e-03
H.s.neandertal_MG025537                8.195952e-04            8.196825e-04
H.s.neandertal_KX198087                7.705439e-04            7.706312e-04
H.s.neandertal_KX198082                7.538130e-04            7.539003e-04
H.s.neandertal_FM865408                7.102830e-04            7.103703e-04
H.s.neandertal_KU131206                1.296191e-03            1.296279e-03
H.s.neandertal_KF982693                1.555714e-03            1.555801e-03
H.s.neandertal_FM865411                2.975685e-03            2.975772e-03
H.s.neandertal_KY751400                6.839229e-03            6.839316e-03
H.s.neandertal_MK033602                3.076743e-03            3.076831e-03
H.s.modern_EU092846                    1.298005e-02            1.298013e-02
H.s.modern_EU092665                    1.223490e-02            1.223499e-02
H.s.modern_JQ045086                    1.272888e-02            1.272897e-02
H.s.modern_DQ779927                    1.235037e-02            1.235045e-02
H.s.modern_DQ779932                    1.236151e-02            1.236160e-02
H.s.modern_AP008640                    1.236327e-02            1.236336e-02
H.s.modern_AY495317                    1.259641e-02            1.259650e-02
H.s.modern_J01415                      1.248842e-02            1.248851e-02
H.s.modern_FJ236981                    1.211129e-02            1.211138e-02
                            H.s.neandertal_MG025538 H.s.neandertal_NC_011137
G.gorilla_D38114                       1.156743e-01             0.1155167337
P.troglodytes_JF727212                 9.314018e-02             0.0929825731
P.troglodytes_JN191207                 8.963564e-02             0.0894780418
P.troglodytes_JF727168                 8.984445e-02             0.0896868484
P.troglodytes_HM068590                 9.023599e-02             0.0900783909
P.paniscus_KX211934                    9.153106e-02             0.0913734547
P.paniscus_KX211928                    9.227350e-02             0.0921158929
P.paniscus_GU189658                    9.098224e-02             0.0908246345
P.paniscus_GU189664                    9.147885e-02             0.0913212501
H.heidelbergensis_NC_023100            1.756465e-02             0.0174070506
H.s.denisova_NC_013993                 2.313758e-02             0.0229799724
H.s.denisova_FR695060                  2.313699e-02             0.0229793866
H.s.denisova_KX663333                  2.107606e-02             0.0209184615
H.s.denisova_KT780370                  2.186384e-02             0.0217062399
H.s.neandertal_KX198085                6.040775e-05             0.0003624617
H.s.neandertal_KX198086                6.049507e-05             0.0003625490
H.s.neandertal_MG025538                0.000000e+00             0.0003017204
H.s.neandertal_NC_011137               3.017204e-04             0.0000000000
H.s.neandertal_FM865409                7.302106e-04             0.0005726079
H.s.neandertal_FM865407                9.073106e-04             0.0007497079
H.s.neandertal_KX198088                9.309671e-04             0.0007733644
H.s.neandertal_KX198083                9.303033e-04             0.0007727006
H.s.neandertal_MG025540                6.028124e-05             0.0003623352
H.s.neandertal_MG025536                2.688137e-03             0.0025305343
H.s.neandertal_MG025537                7.588539e-04             0.0006012512
H.s.neandertal_KX198087                7.098026e-04             0.0005521999
H.s.neandertal_KX198082                6.930717e-04             0.0005354690
H.s.neandertal_FM865408                6.495418e-04             0.0004919391
H.s.neandertal_KU131206                1.235450e-03             0.0010778472
H.s.neandertal_KF982693                1.494972e-03             0.0013373697
H.s.neandertal_FM865411                2.914943e-03             0.0027573408
H.s.neandertal_KY751400                6.778488e-03             0.0066208848
H.s.neandertal_MK033602                3.016002e-03             0.0028583995
H.s.modern_EU092846                    1.291930e-02             0.0127617015
H.s.modern_EU092665                    1.217416e-02             0.0120165593
H.s.modern_JQ045086                    1.266814e-02             0.0125105387
H.s.modern_DQ779927                    1.228963e-02             0.0121320234
H.s.modern_DQ779932                    1.230077e-02             0.0121431678
H.s.modern_AP008640                    1.230253e-02             0.0121449288
H.s.modern_AY495317                    1.253567e-02             0.0123780665
H.s.modern_J01415                      1.242768e-02             0.0122700793
H.s.modern_FJ236981                    1.205055e-02             0.0118929469
                            H.s.neandertal_FM865409 H.s.neandertal_FM865407
G.gorilla_D38114                       0.1154097081            1.153725e-01
P.troglodytes_JF727212                 0.0928755475            9.283834e-02
P.troglodytes_JN191207                 0.0893710162            8.933381e-02
P.troglodytes_JF727168                 0.0895798228            8.954262e-02
P.troglodytes_HM068590                 0.0899713653            8.993416e-02
P.paniscus_KX211934                    0.0912664291            9.122922e-02
P.paniscus_KX211928                    0.0920088674            9.197166e-02
P.paniscus_GU189658                    0.0907176089            9.068040e-02
P.paniscus_GU189664                    0.0912142245            9.117702e-02
H.heidelbergensis_NC_023100            0.0173000250            1.726282e-02
H.s.denisova_NC_013993                 0.0228729468            2.283574e-02
H.s.denisova_FR695060                  0.0228723610            2.283516e-02
H.s.denisova_KX663333                  0.0208114359            2.077423e-02
H.s.denisova_KT780370                  0.0215992143            2.156201e-02
H.s.neandertal_KX198085                0.0007909519            9.680519e-04
H.s.neandertal_KX198086                0.0007910392            9.681392e-04
H.s.neandertal_MG025538                0.0007302106            9.073106e-04
H.s.neandertal_NC_011137               0.0005726079            7.497079e-04
H.s.neandertal_FM865409                0.0000000000            6.426823e-04
H.s.neandertal_FM865407                0.0006426823            0.000000e+00
H.s.neandertal_KX198088                0.0006663388            6.075399e-05
H.s.neandertal_KX198083                0.0006656750            6.009020e-05
H.s.neandertal_MG025540                0.0007908253            9.679254e-04
H.s.neandertal_MG025536                0.0024235087            2.386304e-03
H.s.neandertal_MG025537                0.0004226814            6.713257e-04
H.s.neandertal_KX198087                0.0004082835            6.222743e-04
H.s.neandertal_KX198082                0.0004284435           -1.166229e-05
H.s.neandertal_FM865408                0.0003480227            5.620135e-04
H.s.neandertal_KU131206                0.0009708216            9.336165e-04
H.s.neandertal_KF982693                0.0012303441            1.193139e-03
H.s.neandertal_FM865411                0.0026503152            2.613110e-03
H.s.neandertal_KY751400                0.0065138592            6.476654e-03
H.s.neandertal_MK033602                0.0027513739            2.714169e-03
H.s.modern_EU092846                    0.0126546759            1.261747e-02
H.s.modern_EU092665                    0.0119095337            1.187233e-02
H.s.modern_JQ045086                    0.0124035131            1.236631e-02
H.s.modern_DQ779927                    0.0120249979            1.198779e-02
H.s.modern_DQ779932                    0.0120361422            1.199894e-02
H.s.modern_AP008640                    0.0120379032            1.200070e-02
H.s.modern_AY495317                    0.0122710409            1.223384e-02
H.s.modern_J01415                      0.0121630537            1.212585e-02
H.s.modern_FJ236981                    0.0117859213            1.174872e-02
                            H.s.neandertal_KX198088 H.s.neandertal_KX198083
G.gorilla_D38114                       1.153962e-01            0.1153954957
P.troglodytes_JF727212                 9.286200e-02            0.0928613351
P.troglodytes_JN191207                 8.935747e-02            0.0893568038
P.troglodytes_JF727168                 8.956627e-02            0.0895656104
P.troglodytes_HM068590                 8.995782e-02            0.0899571528
P.paniscus_KX211934                    9.125288e-02            0.0912522167
P.paniscus_KX211928                    9.199532e-02            0.0919946549
P.paniscus_GU189658                    9.070406e-02            0.0907033965
P.paniscus_GU189664                    9.120068e-02            0.0912000121
H.heidelbergensis_NC_023100            1.728648e-02            0.0172858126
H.s.denisova_NC_013993                 2.285940e-02            0.0228587343
H.s.denisova_FR695060                  2.285881e-02            0.0228581486
H.s.denisova_KX663333                  2.079789e-02            0.0207972235
H.s.denisova_KT780370                  2.158567e-02            0.0215850018
H.s.neandertal_KX198085                9.917084e-04            0.0009910446
H.s.neandertal_KX198086                9.917957e-04            0.0009911319
H.s.neandertal_MG025538                9.309671e-04            0.0009303033
H.s.neandertal_NC_011137               7.733644e-04            0.0007727006
H.s.neandertal_FM865409                6.663388e-04            0.0006656750
H.s.neandertal_FM865407                6.075399e-05            0.0000600902
H.s.neandertal_KX198088                0.000000e+00            0.0000000000
H.s.neandertal_KX198083                0.000000e+00            0.0000000000
H.s.neandertal_MG025540                9.915819e-04            0.0009909181
H.s.neandertal_MG025536                2.409960e-03            0.0024092963
H.s.neandertal_MG025537                6.949822e-04            0.0006943184
H.s.neandertal_KX198087                6.459308e-04            0.0006452670
H.s.neandertal_KX198082                1.199418e-05            0.0000113304
H.s.neandertal_FM865408                5.856700e-04            0.0005850062
H.s.neandertal_KU131206                9.572730e-04            0.0009566092
H.s.neandertal_KF982693                1.216795e-03            0.0012161317
H.s.neandertal_FM865411                2.636767e-03            0.0026361028
H.s.neandertal_KY751400                6.500311e-03            0.0064996468
H.s.neandertal_MK033602                2.737825e-03            0.0027371615
H.s.modern_EU092846                    1.264113e-02            0.0126404635
H.s.modern_EU092665                    1.189599e-02            0.0118953213
H.s.modern_JQ045086                    1.238996e-02            0.0123893007
H.s.modern_DQ779927                    1.201145e-02            0.0120107854
H.s.modern_DQ779932                    1.202259e-02            0.0120219298
H.s.modern_AP008640                    1.202435e-02            0.0120236907
H.s.modern_AY495317                    1.225749e-02            0.0122568285
H.s.modern_J01415                      1.214951e-02            0.0121488412
H.s.modern_FJ236981                    1.177237e-02            0.0117717089
                            H.s.neandertal_MG025540 H.s.neandertal_MG025536
G.gorilla_D38114                       1.157350e-01             0.116065812
P.troglodytes_JF727212                 9.320079e-02             0.093531652
P.troglodytes_JN191207                 8.969626e-02             0.090027120
P.troglodytes_JF727168                 8.990507e-02             0.090235927
P.troglodytes_HM068590                 9.029661e-02             0.090627469
P.paniscus_KX211934                    9.159167e-02             0.091922533
P.paniscus_KX211928                    9.233411e-02             0.092664971
P.paniscus_GU189658                    9.104285e-02             0.091373713
P.paniscus_GU189664                    9.153947e-02             0.091870328
H.heidelbergensis_NC_023100            1.762527e-02             0.017956129
H.s.denisova_NC_013993                 2.319819e-02             0.023529051
H.s.denisova_FR695060                  2.319760e-02             0.023528465
H.s.denisova_KX663333                  2.113668e-02             0.021467540
H.s.denisova_KT780370                  2.192446e-02             0.022255318
H.s.neandertal_KX198085               -4.365660e-08             0.002748878
H.s.neandertal_KX198086                4.365660e-08             0.002748966
H.s.neandertal_MG025538                6.028124e-05             0.002688137
H.s.neandertal_NC_011137               3.623352e-04             0.002530534
H.s.neandertal_FM865409                7.908253e-04             0.002423509
H.s.neandertal_FM865407                9.679254e-04             0.002386304
H.s.neandertal_KX198088                9.915819e-04             0.002409960
H.s.neandertal_KX198083                9.909181e-04             0.002409296
H.s.neandertal_MG025540                0.000000e+00             0.002748752
H.s.neandertal_MG025536                2.748752e-03             0.000000000
H.s.neandertal_MG025537                8.194687e-04             0.002452152
H.s.neandertal_KX198087                7.704173e-04             0.002403101
H.s.neandertal_KX198082                7.536865e-04             0.002172065
H.s.neandertal_FM865408                7.101565e-04             0.002342840
H.s.neandertal_KU131206                1.296065e-03             0.001503744
H.s.neandertal_KF982693                1.555587e-03             0.001701599
H.s.neandertal_FM865411                2.975558e-03             0.003306419
H.s.neandertal_KY751400                6.839102e-03             0.007169963
H.s.neandertal_MK033602                3.076617e-03             0.003407478
H.s.modern_EU092846                    1.297992e-02             0.013310780
H.s.modern_EU092665                    1.223478e-02             0.012565638
H.s.modern_JQ045086                    1.272876e-02             0.013059617
H.s.modern_DQ779927                    1.235024e-02             0.012681102
H.s.modern_DQ779932                    1.236139e-02             0.012692246
H.s.modern_AP008640                    1.236315e-02             0.012694007
H.s.modern_AY495317                    1.259628e-02             0.012927145
H.s.modern_J01415                      1.248830e-02             0.012819158
H.s.modern_FJ236981                    1.211116e-02             0.012442025
                            H.s.neandertal_MG025537 H.s.neandertal_KX198087
G.gorilla_D38114                       0.1154383515            1.153893e-01
P.troglodytes_JF727212                 0.0929041909            9.285514e-02
P.troglodytes_JN191207                 0.0893996596            8.935061e-02
P.troglodytes_JF727168                 0.0896084662            8.955941e-02
P.troglodytes_HM068590                 0.0900000086            8.995096e-02
P.paniscus_KX211934                    0.0912950725            9.124602e-02
P.paniscus_KX211928                    0.0920375107            9.198846e-02
P.paniscus_GU189658                    0.0907462523            9.069720e-02
P.paniscus_GU189664                    0.0912428679            9.119382e-02
H.heidelbergensis_NC_023100            0.0173286684            1.727962e-02
H.s.denisova_NC_013993                 0.0229015901            2.285254e-02
H.s.denisova_FR695060                  0.0229010044            2.285195e-02
H.s.denisova_KX663333                  0.0208400793            2.079103e-02
H.s.denisova_KT780370                  0.0216278576            2.157881e-02
H.s.neandertal_KX198085                0.0008195952            7.705439e-04
H.s.neandertal_KX198086                0.0008196825            7.706312e-04
H.s.neandertal_MG025538                0.0007588539            7.098026e-04
H.s.neandertal_NC_011137               0.0006012512            5.521999e-04
H.s.neandertal_FM865409                0.0004226814            4.082835e-04
H.s.neandertal_FM865407                0.0006713257            6.222743e-04
H.s.neandertal_KX198088                0.0006949822            6.459308e-04
H.s.neandertal_KX198083                0.0006943184            6.452670e-04
H.s.neandertal_MG025540                0.0008194687            7.704173e-04
H.s.neandertal_MG025536                0.0024521520            2.403101e-03
H.s.neandertal_MG025537                0.0000000000            4.369268e-04
H.s.neandertal_KX198087                0.0004369268            0.000000e+00
H.s.neandertal_KX198082                0.0004570868            4.080355e-04
H.s.neandertal_FM865408                0.0003766660            6.036485e-05
H.s.neandertal_KU131206                0.0009994650            9.504136e-04
H.s.neandertal_KF982693                0.0012589875            1.209936e-03
H.s.neandertal_FM865411                0.0026789586            2.629907e-03
H.s.neandertal_KY751400                0.0065425026            6.493451e-03
H.s.neandertal_MK033602                0.0027800173            2.730966e-03
H.s.modern_EU092846                    0.0126833193            1.263427e-02
H.s.modern_EU092665                    0.0119381771            1.188913e-02
H.s.modern_JQ045086                    0.0124321565            1.238311e-02
H.s.modern_DQ779927                    0.0120536412            1.200459e-02
H.s.modern_DQ779932                    0.0120647856            1.201573e-02
H.s.modern_AP008640                    0.0120665465            1.201750e-02
H.s.modern_AY495317                    0.0122996843            1.225063e-02
H.s.modern_J01415                      0.0121916970            1.214265e-02
H.s.modern_FJ236981                    0.0118145647            1.176551e-02
                            H.s.neandertal_KX198082 H.s.neandertal_FM865408
G.gorilla_D38114                       1.151583e-01            1.153290e-01
P.troglodytes_JF727212                 9.262410e-02            9.279488e-02
P.troglodytes_JN191207                 8.911957e-02            8.929035e-02
P.troglodytes_JF727168                 8.932838e-02            8.949915e-02
P.troglodytes_HM068590                 8.971992e-02            8.989070e-02
P.paniscus_KX211934                    9.101499e-02            9.118576e-02
P.paniscus_KX211928                    9.175742e-02            9.192820e-02
P.paniscus_GU189658                    9.046616e-02            9.063694e-02
P.paniscus_GU189664                    9.096278e-02            9.113356e-02
H.heidelbergensis_NC_023100            1.704858e-02            1.721936e-02
H.s.denisova_NC_013993                 2.262150e-02            2.279228e-02
H.s.denisova_FR695060                  2.262092e-02            2.279169e-02
H.s.denisova_KX663333                  2.055999e-02            2.073077e-02
H.s.denisova_KT780370                  2.134777e-02            2.151855e-02
H.s.neandertal_KX198085                7.538130e-04            7.102830e-04
H.s.neandertal_KX198086                7.539003e-04            7.103703e-04
H.s.neandertal_MG025538                6.930717e-04            6.495418e-04
H.s.neandertal_NC_011137               5.354690e-04            4.919391e-04
H.s.neandertal_FM865409                4.284435e-04            3.480227e-04
H.s.neandertal_FM865407               -1.166229e-05            5.620135e-04
H.s.neandertal_KX198088                1.199418e-05            5.856700e-04
H.s.neandertal_KX198083                1.133040e-05            5.850062e-04
H.s.neandertal_MG025540                7.536865e-04            7.101565e-04
H.s.neandertal_MG025536                2.172065e-03            2.342840e-03
H.s.neandertal_MG025537                4.570868e-04            3.766660e-04
H.s.neandertal_KX198087                4.080355e-04            6.036485e-05
H.s.neandertal_KX198082                0.000000e+00            3.477746e-04
H.s.neandertal_FM865408                3.477746e-04            0.000000e+00
H.s.neandertal_KU131206                7.193776e-04            8.901528e-04
H.s.neandertal_KF982693                9.789001e-04            1.149675e-03
H.s.neandertal_FM865411                2.398871e-03            2.569646e-03
H.s.neandertal_KY751400                6.262415e-03            6.433190e-03
H.s.neandertal_MK033602                2.499930e-03            2.670705e-03
H.s.modern_EU092846                    1.240323e-02            1.257401e-02
H.s.modern_EU092665                    1.165809e-02            1.182886e-02
H.s.modern_JQ045086                    1.215207e-02            1.232284e-02
H.s.modern_DQ779927                    1.177355e-02            1.194433e-02
H.s.modern_DQ779932                    1.178470e-02            1.195547e-02
H.s.modern_AP008640                    1.178646e-02            1.195723e-02
H.s.modern_AY495317                    1.201960e-02            1.219037e-02
H.s.modern_J01415                      1.191161e-02            1.208238e-02
H.s.modern_FJ236981                    1.153448e-02            1.170525e-02
                            H.s.neandertal_KU131206 H.s.neandertal_KF982693
G.gorilla_D38114                       0.1146131251            0.1148726476
P.troglodytes_JF727212                 0.0920789645            0.0923384870
P.troglodytes_JN191207                 0.0885744332            0.0888339556
P.troglodytes_JF727168                 0.0887832397            0.0890427622
P.troglodytes_HM068590                 0.0891747822            0.0894343047
P.paniscus_KX211934                    0.0904698460            0.0907293685
P.paniscus_KX211928                    0.0912122843            0.0914718068
P.paniscus_GU189658                    0.0899210258            0.0901805483
P.paniscus_GU189664                    0.0904176414            0.0906771639
H.heidelbergensis_NC_023100            0.0165034419            0.0167629644
H.s.denisova_NC_013993                 0.0220763637            0.0223358862
H.s.denisova_FR695060                  0.0220757780            0.0223353005
H.s.denisova_KX663333                  0.0200148529            0.0202743754
H.s.denisova_KT780370                  0.0208026312            0.0210621537
H.s.neandertal_KX198085                0.0012961912            0.0015557137
H.s.neandertal_KX198086                0.0012962785            0.0015558010
H.s.neandertal_MG025538                0.0012354499            0.0014949724
H.s.neandertal_NC_011137               0.0010778472            0.0013373697
H.s.neandertal_FM865409                0.0009708216            0.0012303441
H.s.neandertal_FM865407                0.0009336165            0.0011931390
H.s.neandertal_KX198088                0.0009572730            0.0012167955
H.s.neandertal_KX198083                0.0009566092            0.0012161317
H.s.neandertal_MG025540                0.0012960647            0.0015555872
H.s.neandertal_MG025536                0.0015037445            0.0017015991
H.s.neandertal_MG025537                0.0009994650            0.0012589875
H.s.neandertal_KX198087                0.0009504136            0.0012099361
H.s.neandertal_KX198082                0.0007193776            0.0009789001
H.s.neandertal_FM865408                0.0008901528            0.0011496753
H.s.neandertal_KU131206                0.0000000000            0.0003105799
H.s.neandertal_KF982693                0.0003105799            0.0000000000
H.s.neandertal_FM865411                0.0018537321            0.0021132546
H.s.neandertal_KY751400                0.0057172762            0.0059767986
H.s.neandertal_MK033602                0.0019547909            0.0022143133
H.s.modern_EU092846                    0.0118580929            0.0121176154
H.s.modern_EU092665                    0.0111129507            0.0113724731
H.s.modern_JQ045086                    0.0116069300            0.0118664525
H.s.modern_DQ779927                    0.0112284148            0.0114879373
H.s.modern_DQ779932                    0.0112395592            0.0114990816
H.s.modern_AP008640                    0.0112413201            0.0115008426
H.s.modern_AY495317                    0.0114744579            0.0117339804
H.s.modern_J01415                      0.0113664706            0.0116259931
H.s.modern_FJ236981                    0.0109893382            0.0112488607
                            H.s.neandertal_FM865411 H.s.neandertal_KY751400
G.gorilla_D38114                        0.114885194             0.115521777
P.troglodytes_JF727212                  0.092351034             0.092987616
P.troglodytes_JN191207                  0.088846502             0.089483085
P.troglodytes_JF727168                  0.089055309             0.089691892
P.troglodytes_HM068590                  0.089446851             0.090083434
P.paniscus_KX211934                     0.090741915             0.091378498
P.paniscus_KX211928                     0.091484353             0.092120936
P.paniscus_GU189658                     0.090193095             0.090829678
P.paniscus_GU189664                     0.090689711             0.091326293
H.heidelbergensis_NC_023100             0.016775511             0.017412094
H.s.denisova_NC_013993                  0.022348433             0.022985016
H.s.denisova_FR695060                   0.022347847             0.022984430
H.s.denisova_KX663333                   0.020286922             0.020923505
H.s.denisova_KT780370                   0.021074700             0.021711283
H.s.neandertal_KX198085                 0.002975685             0.006839229
H.s.neandertal_KX198086                 0.002975772             0.006839316
H.s.neandertal_MG025538                 0.002914943             0.006778488
H.s.neandertal_NC_011137                0.002757341             0.006620885
H.s.neandertal_FM865409                 0.002650315             0.006513859
H.s.neandertal_FM865407                 0.002613110             0.006476654
H.s.neandertal_KX198088                 0.002636767             0.006500311
H.s.neandertal_KX198083                 0.002636103             0.006499647
H.s.neandertal_MG025540                 0.002975558             0.006839102
H.s.neandertal_MG025536                 0.003306419             0.007169963
H.s.neandertal_MG025537                 0.002678959             0.006542503
H.s.neandertal_KX198087                 0.002629907             0.006493451
H.s.neandertal_KX198082                 0.002398871             0.006262415
H.s.neandertal_FM865408                 0.002569646             0.006433190
H.s.neandertal_KU131206                 0.001853732             0.005717276
H.s.neandertal_KF982693                 0.002113255             0.005976799
H.s.neandertal_FM865411                 0.000000000             0.005989345
H.s.neandertal_KY751400                 0.005989345             0.000000000
H.s.neandertal_MK033602                 0.001995112             0.006090404
H.s.modern_EU092846                     0.012130162             0.012766745
H.s.modern_EU092665                     0.011385020             0.012021603
H.s.modern_JQ045086                     0.011878999             0.012515582
H.s.modern_DQ779927                     0.011500484             0.012137067
H.s.modern_DQ779932                     0.011511628             0.012148211
H.s.modern_AP008640                     0.011513389             0.012149972
H.s.modern_AY495317                     0.011746527             0.012383110
H.s.modern_J01415                       0.011638540             0.012275122
H.s.modern_FJ236981                     0.011261407             0.011897990
                            H.s.neandertal_MK033602 H.s.modern_EU092846
G.gorilla_D38114                        0.114986253         0.116261671
P.troglodytes_JF727212                  0.092452092         0.093727510
P.troglodytes_JN191207                  0.088947561         0.090222979
P.troglodytes_JF727168                  0.089156368         0.090431785
P.troglodytes_HM068590                  0.089547910         0.090823328
P.paniscus_KX211934                     0.090842974         0.092118392
P.paniscus_KX211928                     0.091585412         0.092860830
P.paniscus_GU189658                     0.090294154         0.091569571
P.paniscus_GU189664                     0.090790769         0.092066187
H.heidelbergensis_NC_023100             0.016876570         0.018151987
H.s.denisova_NC_013993                  0.022449492         0.023724909
H.s.denisova_FR695060                   0.022448906         0.023724323
H.s.denisova_KX663333                   0.020387981         0.021663398
H.s.denisova_KT780370                   0.021175759         0.022451177
H.s.neandertal_KX198085                 0.003076743         0.012980046
H.s.neandertal_KX198086                 0.003076831         0.012980133
H.s.neandertal_MG025538                 0.003016002         0.012919304
H.s.neandertal_NC_011137                0.002858400         0.012761702
H.s.neandertal_FM865409                 0.002751374         0.012654676
H.s.neandertal_FM865407                 0.002714169         0.012617471
H.s.neandertal_KX198088                 0.002737825         0.012641127
H.s.neandertal_KX198083                 0.002737161         0.012640464
H.s.neandertal_MG025540                 0.003076617         0.012979919
H.s.neandertal_MG025536                 0.003407478         0.013310780
H.s.neandertal_MG025537                 0.002780017         0.012683319
H.s.neandertal_KX198087                 0.002730966         0.012634268
H.s.neandertal_KX198082                 0.002499930         0.012403232
H.s.neandertal_FM865408                 0.002670705         0.012574007
H.s.neandertal_KU131206                 0.001954791         0.011858093
H.s.neandertal_KF982693                 0.002214313         0.012117615
H.s.neandertal_FM865411                 0.001995112         0.012130162
H.s.neandertal_KY751400                 0.006090404         0.012766745
H.s.neandertal_MK033602                 0.000000000         0.012231221
H.s.modern_EU092846                     0.012231221         0.000000000
H.s.modern_EU092665                     0.011486079         0.004115877
H.s.modern_JQ045086                     0.011980058         0.005945487
H.s.modern_DQ779927                     0.011601543         0.005566971
H.s.modern_DQ779932                     0.011612687         0.005578116
H.s.modern_AP008640                     0.011614448         0.005579877
H.s.modern_AY495317                     0.011847586         0.005813014
H.s.modern_J01415                       0.011739598         0.005705027
H.s.modern_FJ236981                     0.011362466         0.005327895
                            H.s.modern_EU092665 H.s.modern_JQ045086
G.gorilla_D38114                    0.115516528         0.116010508
P.troglodytes_JF727212              0.092982368         0.093476347
P.troglodytes_JN191207              0.089477836         0.089971816
P.troglodytes_JF727168              0.089686643         0.090180622
P.troglodytes_HM068590              0.090078185         0.090572165
P.paniscus_KX211934                 0.091373249         0.091867229
P.paniscus_KX211928                 0.092115688         0.092609667
P.paniscus_GU189658                 0.090824429         0.091318409
P.paniscus_GU189664                 0.091321045         0.091815024
H.heidelbergensis_NC_023100         0.017406845         0.017900825
H.s.denisova_NC_013993              0.022979767         0.023473746
H.s.denisova_FR695060               0.022979181         0.023473161
H.s.denisova_KX663333               0.020918256         0.021412236
H.s.denisova_KT780370               0.021706034         0.022200014
H.s.neandertal_KX198085             0.012234903         0.012728883
H.s.neandertal_KX198086             0.012234991         0.012728970
H.s.neandertal_MG025538             0.012174162         0.012668141
H.s.neandertal_NC_011137            0.012016559         0.012510539
H.s.neandertal_FM865409             0.011909534         0.012403513
H.s.neandertal_FM865407             0.011872329         0.012366308
H.s.neandertal_KX198088             0.011895985         0.012389964
H.s.neandertal_KX198083             0.011895321         0.012389301
H.s.neandertal_MG025540             0.012234777         0.012728756
H.s.neandertal_MG025536             0.012565638         0.013059617
H.s.neandertal_MG025537             0.011938177         0.012432156
H.s.neandertal_KX198087             0.011889126         0.012383105
H.s.neandertal_KX198082             0.011658090         0.012152069
H.s.neandertal_FM865408             0.011828865         0.012322844
H.s.neandertal_KU131206             0.011112951         0.011606930
H.s.neandertal_KF982693             0.011372473         0.011866453
H.s.neandertal_FM865411             0.011385020         0.011878999
H.s.neandertal_KY751400             0.012021603         0.012515582
H.s.neandertal_MK033602             0.011486079         0.011980058
H.s.modern_EU092846                 0.004115877         0.005945487
H.s.modern_EU092665                 0.000000000         0.005200344
H.s.modern_JQ045086                 0.005200344         0.000000000
H.s.modern_DQ779927                 0.004821829         0.004762741
H.s.modern_DQ779932                 0.004832973         0.004773886
H.s.modern_AP008640                 0.004834734         0.004775647
H.s.modern_AY495317                 0.005067872         0.005008784
H.s.modern_J01415                   0.004959885         0.004900797
H.s.modern_FJ236981                 0.004582753         0.004523665
                            H.s.modern_DQ779927 H.s.modern_DQ779932
G.gorilla_D38114                    0.115631992         0.115643137
P.troglodytes_JF727212              0.093097832         0.093108976
P.troglodytes_JN191207              0.089593301         0.089604445
P.troglodytes_JF727168              0.089802107         0.089813252
P.troglodytes_HM068590              0.090193650         0.090204794
P.paniscus_KX211934                 0.091488713         0.091499858
P.paniscus_KX211928                 0.092231152         0.092242296
P.paniscus_GU189658                 0.090939893         0.090951038
P.paniscus_GU189664                 0.091436509         0.091447653
H.heidelbergensis_NC_023100         0.017522309         0.017533454
H.s.denisova_NC_013993              0.023095231         0.023106375
H.s.denisova_FR695060               0.023094645         0.023105790
H.s.denisova_KX663333               0.021033720         0.021044865
H.s.denisova_KT780370               0.021821499         0.021832643
H.s.neandertal_KX198085             0.012350367         0.012361512
H.s.neandertal_KX198086             0.012350455         0.012361599
H.s.neandertal_MG025538             0.012289626         0.012300771
H.s.neandertal_NC_011137            0.012132023         0.012143168
H.s.neandertal_FM865409             0.012024998         0.012036142
H.s.neandertal_FM865407             0.011987793         0.011998937
H.s.neandertal_KX198088             0.012011449         0.012022594
H.s.neandertal_KX198083             0.012010785         0.012021930
H.s.neandertal_MG025540             0.012350241         0.012361385
H.s.neandertal_MG025536             0.012681102         0.012692246
H.s.neandertal_MG025537             0.012053641         0.012064786
H.s.neandertal_KX198087             0.012004590         0.012015734
H.s.neandertal_KX198082             0.011773554         0.011784698
H.s.neandertal_FM865408             0.011944329         0.011955473
H.s.neandertal_KU131206             0.011228415         0.011239559
H.s.neandertal_KF982693             0.011487937         0.011499082
H.s.neandertal_FM865411             0.011500484         0.011511628
H.s.neandertal_KY751400             0.012137067         0.012148211
H.s.neandertal_MK033602             0.011601543         0.011612687
H.s.modern_EU092846                 0.005566971         0.005578116
H.s.modern_EU092665                 0.004821829         0.004832973
H.s.modern_JQ045086                 0.004762741         0.004773886
H.s.modern_DQ779927                 0.000000000         0.001087163
H.s.modern_DQ779932                 0.001087163         0.000000000
H.s.modern_AP008640                 0.002348508         0.002359653
H.s.modern_AY495317                 0.002581646         0.002592791
H.s.modern_J01415                   0.002473659         0.002484803
H.s.modern_FJ236981                 0.002096527         0.002107671
                            H.s.modern_AP008640 H.s.modern_AY495317
G.gorilla_D38114                    0.115644898        0.1158780356
P.troglodytes_JF727212              0.093110737        0.0933438750
P.troglodytes_JN191207              0.089606206        0.0898393436
P.troglodytes_JF727168              0.089815012        0.0900481502
P.troglodytes_HM068590              0.090206555        0.0904396927
P.paniscus_KX211934                 0.091501619        0.0917347565
P.paniscus_KX211928                 0.092244057        0.0924771948
P.paniscus_GU189658                 0.090952799        0.0911859363
P.paniscus_GU189664                 0.091449414        0.0916825519
H.heidelbergensis_NC_023100         0.017535215        0.0177683524
H.s.denisova_NC_013993              0.023108136        0.0233412742
H.s.denisova_FR695060               0.023107551        0.0233406885
H.s.denisova_KX663333               0.021046626        0.0212797634
H.s.denisova_KT780370               0.021834404        0.0220675417
H.s.neandertal_KX198085             0.012363273        0.0125964105
H.s.neandertal_KX198086             0.012363360        0.0125964978
H.s.neandertal_MG025538             0.012302531        0.0125356692
H.s.neandertal_NC_011137            0.012144929        0.0123780665
H.s.neandertal_FM865409             0.012037903        0.0122710409
H.s.neandertal_FM865407             0.012000698        0.0122338358
H.s.neandertal_KX198088             0.012024355        0.0122574923
H.s.neandertal_KX198083             0.012023691        0.0122568285
H.s.neandertal_MG025540             0.012363146        0.0125962840
H.s.neandertal_MG025536             0.012694007        0.0129271449
H.s.neandertal_MG025537             0.012066547        0.0122996843
H.s.neandertal_KX198087             0.012017495        0.0122506329
H.s.neandertal_KX198082             0.011786459        0.0120195969
H.s.neandertal_FM865408             0.011957234        0.0121903721
H.s.neandertal_KU131206             0.011241320        0.0114744579
H.s.neandertal_KF982693             0.011500843        0.0117339804
H.s.neandertal_FM865411             0.011513389        0.0117465270
H.s.neandertal_KY751400             0.012149972        0.0123831098
H.s.neandertal_MK033602             0.011614448        0.0118475858
H.s.modern_EU092846                 0.005579877        0.0058130144
H.s.modern_EU092665                 0.004834734        0.0050678722
H.s.modern_JQ045086                 0.004775647        0.0050087845
H.s.modern_DQ779927                 0.002348508        0.0025816461
H.s.modern_DQ779932                 0.002359653        0.0025927905
H.s.modern_AP008640                 0.000000000        0.0017507900
H.s.modern_AY495317                 0.001750790        0.0000000000
H.s.modern_J01415                   0.001642803        0.0010873068
H.s.modern_FJ236981                 0.001265670        0.0008390806
                            H.s.modern_J01415 H.s.modern_FJ236981
G.gorilla_D38114                 0.1157700483        0.1153929159
P.troglodytes_JF727212           0.0932358877        0.0928587553
P.troglodytes_JN191207           0.0897313564        0.0893542240
P.troglodytes_JF727168           0.0899401630        0.0895630306
P.troglodytes_HM068590           0.0903317054        0.0899545731
P.paniscus_KX211934              0.0916267692        0.0912496369
P.paniscus_KX211928              0.0923692075        0.0919920751
P.paniscus_GU189658              0.0910779491        0.0907008167
P.paniscus_GU189664              0.0915745646        0.0911974323
H.heidelbergensis_NC_023100      0.0176603651        0.0172832328
H.s.denisova_NC_013993           0.0232332869        0.0228561545
H.s.denisova_FR695060            0.0232327012        0.0228555688
H.s.denisova_KX663333            0.0211717761        0.0207946437
H.s.denisova_KT780370            0.0219595544        0.0215824221
H.s.neandertal_KX198085          0.0124884232        0.0121112909
H.s.neandertal_KX198086          0.0124885105        0.0121113782
H.s.neandertal_MG025538          0.0124276820        0.0120505496
H.s.neandertal_NC_011137         0.0122700793        0.0118929469
H.s.neandertal_FM865409          0.0121630537        0.0117859213
H.s.neandertal_FM865407          0.0121258486        0.0117487162
H.s.neandertal_KX198088          0.0121495050        0.0117723727
H.s.neandertal_KX198083          0.0121488412        0.0117717089
H.s.neandertal_MG025540          0.0124882967        0.0121111643
H.s.neandertal_MG025536          0.0128191576        0.0124420253
H.s.neandertal_MG025537          0.0121916970        0.0118145647
H.s.neandertal_KX198087          0.0121426457        0.0117655133
H.s.neandertal_KX198082          0.0119116097        0.0115344773
H.s.neandertal_FM865408          0.0120823849        0.0117052525
H.s.neandertal_KU131206          0.0113664706        0.0109893382
H.s.neandertal_KF982693          0.0116259931        0.0112488607
H.s.neandertal_FM865411          0.0116385398        0.0112614074
H.s.neandertal_KY751400          0.0122751225        0.0118979901
H.s.neandertal_MK033602          0.0117395985        0.0113624661
H.s.modern_EU092846              0.0057050271        0.0053278947
H.s.modern_EU092665              0.0049598849        0.0045827525
H.s.modern_JQ045086              0.0049007972        0.0045236649
H.s.modern_DQ779927              0.0024736589        0.0020965265
H.s.modern_DQ779932              0.0024848032        0.0021076709
H.s.modern_AP008640              0.0016428027        0.0012656703
H.s.modern_AY495317              0.0010873068        0.0008390806
H.s.modern_J01415                0.0000000000        0.0007310934
H.s.modern_FJ236981              0.0007310934        0.0000000000</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ejercicio
</div>
</div>
<div class="callout-body-container callout-body">
<p>¿Cuánto se parecen las distancias estimadas a las distancias cofenéticas?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(distancias, <span class="fu">as.dist</span>(distCofen))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9999345</code></pre>
</div>
</div>
<p>Se parecen mucho, eso significa que el árbol representa de forma precisa las distancias genéticas reales obseervadas en el alineamiento.</p>
</div>
</div>
</section>
<section id="limpieza-o-filtrado-del-alineamiento" class="level1">
<h1>Limpieza o filtrado del alineamiento</h1>
<p>Las distancias crudas, como número de diferencias, nos pueden informar de la presencia de pares de secuencias idénticas. Podríamos dejarlas, pero algunos de los métodos que usaremos a continuación pueden generar errores, por ejemplo cuando dos secuencias idénticas se supone que pertenecen a épocas diferentes.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>crudas <span class="ot">&lt;-</span> <span class="fu">dist.dna</span>(<span class="fu">as.DNAbin</span>(mtdna), <span class="at">model =</span> <span class="st">'raw'</span>)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>crudas <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(crudas)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>identicas <span class="ot">&lt;-</span> <span class="fu">which</span>(crudas <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> <span class="fu">lower.tri</span>(crudas), <span class="at">arr.ind =</span> <span class="cn">TRUE</span>)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="co"># posiciones de la semimatriz inferior donde las distancias son 0:</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>identicas</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        row col
H.s.neandertal_KX198086  16  15
H.s.neandertal_MG025540  23  15
H.s.neandertal_MG025540  23  16
H.s.neandertal_KX198088  21  20
H.s.neandertal_KX198083  22  20
H.s.neandertal_KX198082  27  20
H.s.neandertal_KX198083  22  21
H.s.neandertal_KX198082  27  21
H.s.neandertal_KX198082  27  22</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>repetidas <span class="ot">&lt;-</span> <span class="fu">unique</span>(<span class="fu">c</span>(identicas[, <span class="st">'row'</span>], identicas[, <span class="st">'col'</span>]))</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">heatmap</span>(crudas[repetidas, repetidas], <span class="at">cexRow =</span> <span class="fl">0.7</span>, <span class="at">cexCol =</span> <span class="fl">0.7</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="guion9_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Así pues, las secuencias de Neandertales KX198085, KX198086 y MG025540 (todas ellas con una edad estimada de unos 40000 años) son idénticas entre ellas; y las secuencias, también Neandertales FM865407, KX198082, KX198088 y KX198083 son idénticas entre ellas. Bueno, en realidad, la comparación ignora las posiciones en las que una secuencia contiene ambigüedades (Ns). Dejaremos sólo una de cada grupo: MG025540 y FM865407, que son las que menos ambigüedades tienen en la secuencia. Como no conocemos una función que elimine secuencias de un objeto <code>phyDat</code>, necesitamos especificar aquellas con las que nos queremos quedar. Podríamos usar la función <code>subset()</code> o bien la función <code>[</code>, tal como la aplicaríamos a una matriz. También existe una función <code>unique()</code>, pero si la usamos perdemos control sobre qué representantes conservamos de cada grupo de secuencias idénticas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># La exclamación ("!") invierte el valor lógico de lo que la sigue.</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="co"># La función "grepl()" produce un vector lógico con "TRUE" donde los nombres</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="co"># de las secuencias contienen alguna de esas palabras.</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>mtdna37 <span class="ot">&lt;-</span> mtdna[<span class="sc">!</span> <span class="fu">grepl</span>(<span class="st">'(KX198085|KX198086|KX198082|KX198088|KX198083)'</span>,</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">names</span>(mtdna)), ]</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>mtdna37</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>37 sequences with 16603 character and 974 different site patterns.
The states are a c g t </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ejercicio
</div>
</div>
<div class="callout-body-container callout-body">
<p>¿Serías capaz de crear otro conjunto de datos, mtdna28, que sólo contenga secuencias del género Homo?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>mtdna28 <span class="ot">&lt;-</span> mtdna[<span class="fu">startsWith</span>(<span class="fu">names</span>(mtdna), <span class="st">"H."</span>)]</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>mtdna28</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>33 sequences with 16603 character and 974 different site patterns.
The states are a c g t </code></pre>
</div>
</div>
</div>
</div>
<p>Por otra parte, la secuencia del gorila no nos hace falta: es demasiado divergente y puede haber evolucionado a un ritmo diferente.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>mtdna36 <span class="ot">&lt;-</span> mtdna37[<span class="sc">!</span> <span class="fu">startsWith</span>(<span class="fu">names</span>(mtdna37), <span class="st">'G.gorilla'</span>),]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="escoger-el-modelo-de-evolución-molecular" class="level2">
<h2 class="anchored" data-anchor-id="escoger-el-modelo-de-evolución-molecular">Escoger el modelo de evolución molecular</h2>
<p>Las secuencias mitocondriales proporcionan suficiente información para determinar con confianza la topología del árbol que relaciona los grupos principales. Sólo algunas regiones de árbol, como la relación exacta entre los miembros de un mismo grupo, presentan dificultad. Para estimar mejor la topología y las longitudes de las ramas, debemos usar el método de máxima verosimilitud, para el cual sí es fundamental escoger el modelo evolutivo más adecuado. Para ello usamos la funcion modelTest(), que devuelve un objeto de clase modelTest, que también puede usarse como un simple marco de datos.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>modelos <span class="ot">&lt;-</span> <span class="fu">modelTest</span>(mtdna36, <span class="at">control =</span> <span class="fu">pml.control</span>(<span class="at">trace =</span> <span class="dv">0</span>))</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(modelos)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Model df    logLik      AIC AICw     AICc AICcw      BIC
1        JC 69 -43393.51 86925.02    0 86925.60     0 87457.51
2      JC+I 70 -42830.37 85800.74    0 85801.35     0 86340.96
3   JC+G(4) 70 -42826.86 85793.72    0 85794.32     0 86333.93
4 JC+G(4)+I 71 -42806.58 85755.15    0 85755.77     0 86303.08
5       F81 72 -42566.50 85277.01    0 85277.64     0 85832.66
6     F81+I 73 -41986.64 84119.29    0 84119.94     0 84682.65</code></pre>
</div>
</div>
<p>Si tienes más de un procesador (y si tienes el paquete parallel instalado), puedes pedirle que los use:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>modelos <span class="ot">&lt;-</span> <span class="fu">modelTest</span>(mtdna36, <span class="at">control =</span> <span class="fu">pml.control</span>(<span class="at">trace =</span> <span class="dv">0</span>),</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">multicore =</span> <span class="cn">TRUE</span>, <span class="at">mc.cores =</span> <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Lo que hace modelTest() es calcular la verosimilitud de cada modelo sobre un mismo árbol. Al hacerlo, debe optimizar los parámetros de cada modelo, pero no optimiza el árbol. Sería una pérdida de tiempo no guardar los parámetros optimizados, que son un excelente punto de partida para la búsqueda del árbol más verosímil. Podemos extraer cualquiera de los modelos comparados con la función as.pml():</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">as.pml</span>(modelos, <span class="st">'GTR+G(4)+I'</span>)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>fit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>model: GTR+G(4)+I 
loglikelihood: -39275.11 
unconstrained loglikelihood: -45918.42 
Proportion of invariant sites: 0.6583584 
Model of rate heterogeneity: Discrete gamma model
Number of rate categories: 4 
Shape parameter: 0.9797907 
       Rate Proportion
1 0.0000000  0.6583584
2 0.3890161  0.0854104
3 1.3774436  0.0854104
4 2.9170014  0.0854104
5 7.0247155  0.0854104

Rate matrix:
          a          c          g         t
a  0.000000  1.9682559 63.0009210  1.212887
c  1.968256  0.0000000  0.6641106 46.671197
g 63.000921  0.6641106  0.0000000  1.000000
t  1.212887 46.6711971  1.0000000  0.000000

Base frequencies:  
        a         c         g         t 
0.3094827 0.3112863 0.1305929 0.2486381 </code></pre>
</div>
</div>
<p>Aquí se demuestra que modelos no es un simple marco de datos, sino que tiene escondida mucha información, incluyendo de hecho el árbol y el alineamiento.</p>
<p>También podemos usar as.pml() para extraer el modelo más adecuado a los datos según alguno de los criterios disponibles (BIC, AIC, AICc). El motivo por el que el modelo más adecuado no es necesariamente el más verosímil es que la verosimilitud siempre será mayor para un modelo más complejo (con más parámetros), porque tiene más grados de libertad para ajustarse a los datos. Los criterios de selección penalizan los modelos con más parámetros para hacer la comparación más justa. El peligro de usar un modelo con demasiados parámetros es el de sobreajustar el modelo, es decir, tomar el ruído natural de los datos como algo que el modelo también debe explicar.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">as.pml</span>(modelos, <span class="st">'BIC'</span>)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>fit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>model: TIM2+G(4)+I 
loglikelihood: -39278.26 
unconstrained loglikelihood: -45918.42 
Proportion of invariant sites: 0.6579268 
Model of rate heterogeneity: Discrete gamma model
Number of rate categories: 4 
Shape parameter: 0.9785264 
       Rate Proportion
1 0.0000000  0.6579268
2 0.3877814  0.0855183
3 1.3745623  0.0855183
4 2.9126772  0.0855183
5 7.0183835  0.0855183

Rate matrix:
          a         c        g         t
a  0.000000  2.033328 78.09853  2.033328
c  2.033328  0.000000  1.00000 57.925286
g 78.098529  1.000000  0.00000  1.000000
t  2.033328 57.925286  1.00000  0.000000

Base frequencies:  
        a         c         g         t 
0.3094827 0.3112863 0.1305929 0.2486381 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ejercicio
</div>
</div>
<div class="callout-body-container callout-body">
<p>¿Cuál es el mejor modelo para secuencias sólo del género Homo?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>modelos2 <span class="ot">&lt;-</span> <span class="fu">modelTest</span>(mtdna28, <span class="at">control =</span> <span class="fu">pml.control</span>(<span class="at">trace =</span> <span class="dv">0</span>))</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(modelos2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Model df    logLik      AIC AICw     AICc AICcw      BIC
1        JC 63 -30759.41 61644.82    0 61645.31     0 62131.01
2      JC+I 64 -30515.58 61159.16    0 61159.67     0 61653.07
3   JC+G(4) 64 -30565.83 61259.66    0 61260.16     0 61753.57
4 JC+G(4)+I 65 -30508.90 61147.80    0 61148.31     0 61649.42
5       F81 66 -29972.64 60077.28    0 60077.82     0 60586.63
6     F81+I 67 -29732.53 59599.05    0 59599.60     0 60116.11</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">as.pml</span>(modelos2, <span class="st">'BIC'</span>)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>fit2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>model: TrN+G(4)+I 
loglikelihood: -28834.76 
unconstrained loglikelihood: -45918.42 
Proportion of invariant sites: 0.814369 
Model of rate heterogeneity: Discrete gamma model
Number of rate categories: 4 
Shape parameter: 1.00375 
        Rate Proportion
1  0.0000000 0.81436900
2  0.7418019 0.04640775
3  2.5743337 0.04640775
4  5.3903638 0.04640775
5 12.8416261 0.04640775

Rate matrix:
         a        c        g        t
a  0.00000  1.00000 53.82462  1.00000
c  1.00000  0.00000  1.00000 32.13628
g 53.82462  1.00000  0.00000  1.00000
t  1.00000 32.13628  1.00000  0.00000

Base frequencies:  
        a         c         g         t 
0.3087990 0.3122807 0.1312409 0.2476795 </code></pre>
</div>
</div>
<p>como BIC es menor en este <code>(modelos2)</code>este es el mejor modelo.</p>
</div>
</div>
</section>
</section>
<section id="máxima-verosimilitud" class="level1">
<h1>Máxima verosimilitud</h1>
<p>Una vez hemos seleccionado el modelo, podemos optimizar la topología del árbol, sus longitudes de ramas, y también los demás parámetros del modelo. Para ello, usaremos la función pml_bb(), que internamente usa las funciones pml() y optim.pml(). Podemos modular el comportamiento de pml_bb() (cuánta información muestra del proceso, cuántas iteraciones usa, cuándo decide que no puede mejorar el modelo…) con los parámetros definidos mediante pml.control(). A la función pml_bb() podemos proporcionarle el alineamiento (objeto de clase phyDat) y el nombre del modelo de evolución molecular, o bien un objeto de clase modelTest, de donde toma automáticamente el alineamiento y el modelo con un valor de BIC (Bayesian Information Criterion) más bajo.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>mt_ml <span class="ot">&lt;-</span> <span class="fu">pml_bb</span>(modelos,</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">control =</span> <span class="fu">pml.control</span>(<span class="at">trace =</span> <span class="dv">0</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>El objeto mt_ml, de clase pml, contiene el árbol (mt_ml$tree), además de los parámetros optimizados del modelo. Antes de ver el árbol, echémosle un vistazo al modelo ajustado, para ver cuánto se aparta del que habíamos ajustado con modelTest().</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>mt_ml</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>model: TIM2+G(4)+I 
loglikelihood: -39277.23 
unconstrained loglikelihood: -45918.42 
Proportion of invariant sites: 0.657575 
Model of rate heterogeneity: Discrete gamma model
Number of rate categories: 4 
Shape parameter: 0.9767082 
       Rate Proportion
1 0.0000000 0.65757501
2 0.3863134 0.08560625
3 1.3715038 0.08560625
4 2.9087562 0.08560625
5 7.0148169 0.08560625

Rate matrix:
          a         c        g         t
a  0.000000  2.032833 77.89996  2.032833
c  2.032833  0.000000  1.00000 57.982093
g 77.899959  1.000000  0.00000  1.000000
t  2.032833 57.982093  1.00000  0.000000

Base frequencies:  
        a         c         g         t 
0.3094827 0.3112863 0.1305929 0.2486381 </code></pre>
</div>
</div>
<p>Por defecto, pml_bb() usa un método de reordenación del árbol denominado “stochastic”, genera un árbol no enraizado y 1000 pseudo-réplicas de bootstrap. Al pedirle la representación gráfica, añade automáticamente los valores de soporte de bootstrap y lo enraiza en el punto medio:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mt_ml, <span class="at">align.tip.label =</span> <span class="cn">TRUE</span>, <span class="at">main =</span> <span class="st">'Árbol más verosímil'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="guion9_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ejercicio
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>El árbol no está enraizado. Como las secuencias no son todas de la misma época, utiliza rtt() para situar la raíz en el punto más compatible con la hipótesis de reloj molecular.</li>
</ul>
<p>vamos a enraizar el arbol:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>fechas36 <span class="ot">&lt;-</span> fechas[<span class="fu">names</span>(mtdna36)]</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>mt_ml_rtt <span class="ot">&lt;-</span> <span class="fu">rtt</span>(mt_ml<span class="sc">$</span>tree, fechas36, <span class="at">objective =</span> <span class="st">"rms"</span>)</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mt_ml_rtt, <span class="at">main =</span> <span class="st">"árbol homo enraizado rtt"</span>)</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a><span class="fu">axisPhylo</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="guion9_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>¿Podrías obtener el árbol más verosímil para el subconjunto de secuencias del género Homo?</li>
</ul>
</div>
</div>
</section>
<section id="con-datación-de-puntas-tip-dating" class="level1">
<h1>Con datación de puntas (tip dating)</h1>
<p>El método de máxima verosimilitud genera árboles no enraizados por defecto, como consecuencia de la reversibilidad temporal. En esos árboles las longitudes de ramas són el número esperado de sustituciones por sitio, sin ninguna referencia explícita al tiempo. Pero cuando no todas las secuencias son isócronas, podemos usar la información de sus edades para constreñir la búsqueda del árbol más verosímil. Al usar las edades de las secuencias, estamos asumiendo un reloj molecular: una relación constante entre el tiempo y el número esperado de sustituciones acumuladas. Entonces, la posición de la raíz afecta la verosimilitud y el resultado es un árbol enraizado.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Habíamos creado el vector "fechas", pero incluye al gorila.</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>fechas36 <span class="ot">&lt;-</span> fechas[<span class="fu">names</span>(mtdna36)]</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>mt_ml_clock <span class="ot">&lt;-</span> <span class="fu">pml_bb</span>(modelos,</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">method =</span> <span class="st">'tipdated'</span>,</span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">tip.dates =</span> fechas36, <span class="at">rearrangement =</span> <span class="st">'NNI'</span>,</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>                      <span class="at">control =</span> <span class="fu">pml.control</span>(<span class="at">trace =</span> <span class="dv">0</span>))</span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>mt_ml_clock</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>model: TIM2+G(4)+I 
loglikelihood: -41234.67 
unconstrained loglikelihood: -45918.42 
Proportion of invariant sites: 0.764226 
Model of rate heterogeneity: Discrete gamma model
Number of rate categories: 4 
Shape parameter: 1.09221 
          Rate Proportion
1 0.000000e+00 0.76422604
2 7.615385e-09 0.05894349
3 2.470784e-08 0.05894349
4 4.981436e-08 0.05894349
5 1.144185e-07 0.05894349

Rate: 1.15857e-08 

Rate matrix:
          a         c        g         t
a  0.000000  2.325799 58.05786  2.325799
c  2.325799  0.000000  1.00000 48.086228
g 58.057862  1.000000  0.00000  1.000000
t  2.325799 48.086228  1.00000  0.000000

Base frequencies:  
        a         c         g         t 
0.3094827 0.3112863 0.1305929 0.2486381 

Rate: 1.15857e-08 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mt_ml_clock, <span class="at">align.tip.label =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="guion9_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ejercicio
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>¿Cuál es la tasa de mutación global estimada?</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>mt_ml_clock</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>model: TIM2+G(4)+I 
loglikelihood: -41234.67 
unconstrained loglikelihood: -45918.42 
Proportion of invariant sites: 0.764226 
Model of rate heterogeneity: Discrete gamma model
Number of rate categories: 4 
Shape parameter: 1.09221 
          Rate Proportion
1 0.000000e+00 0.76422604
2 7.615385e-09 0.05894349
3 2.470784e-08 0.05894349
4 4.981436e-08 0.05894349
5 1.144185e-07 0.05894349

Rate: 1.15857e-08 

Rate matrix:
          a         c        g         t
a  0.000000  2.325799 58.05786  2.325799
c  2.325799  0.000000  1.00000 48.086228
g 58.057862  1.000000  0.00000  1.000000
t  2.325799 48.086228  1.00000  0.000000

Base frequencies:  
        a         c         g         t 
0.3094827 0.3112863 0.1305929 0.2486381 

Rate: 1.15857e-08 </code></pre>
</div>
</div>
<p>rate es 1.15857e-08, esta es la tasa de mutación global</p>
<ul>
<li><p>¿En qué unidades està expresada? está expresada en sustituciones por sitio/año</p></li>
<li><p>¿Cuánto tiempo dice el árbol que divergimos de los chimpancés? (Puedes usar la función cophenetic(), puesto que en el árbol datado las longitudes de las ramas están en años).</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>dist_tiempos <span class="ot">&lt;-</span> <span class="fu">cophenetic</span>(mt_ml_clock<span class="sc">$</span>tree) </span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>fila_humano <span class="ot">&lt;-</span> <span class="fu">grep</span>(<span class="st">"H.s.modern"</span>, <span class="fu">rownames</span>(dist_tiempos))[<span class="dv">1</span>]</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>fila_chimp  <span class="ot">&lt;-</span> <span class="fu">grep</span>(<span class="st">"P.troglodytes"</span>, <span class="fu">rownames</span>(dist_tiempos))[<span class="dv">1</span>]</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>tiempodivergencia <span class="ot">&lt;-</span> dist_tiempos[fila_humano, fila_chimp]<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>tiempodivergencia</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 902089.5</code></pre>
</div>
</div>
</div>
</div>
</section>
<section id="estimación-de-edades" class="level1">
<h1>Estimación de edades</h1>
<p>Las edades de las secuencias aportan información sobre el reloj molecular en la medida en que se echen de menos las mutaciones que dejaron de acumularse en las secuencias arcaicas. Esta información puede ser muy útil en filogenias de virus de ARN muestreados a lo largo de los años. Pero en una filogenia de millones de años, la poca información de las puntas no es suficiente para datar con exactitud las divergencias antiguas. Hay otras estrategias. Podríamos fijar una tasa de mutación conocida y estimar sólo los otros parámetros. Alternativamente, podemos dar la fecha de algún nodo interno para ayudar a calibrar el reloj. Por ejemplo, supondremos que el ancestro común más reciente entre humanos y chimpancés vivió hace 6.5 millones de años.</p>
<p>Esta información se la proporcionamos a la función estimate.dates() mediante un vector de fechas o edades de las secuencias que incluya no sólo las hojas del árbol sino también los nodos internos, o al menos aquellos de los que conocemos la edad. El vector debe tener tantos componentes como nodos internos y hojas tiene el árbol, con valores NA en las edades desconocidas. Para saber en qué orden están numerados los nodos, podemos ejecutar lo siguiente:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>mt_ml_rtt <span class="ot">&lt;-</span> <span class="fu">rtt</span>(mt_ml<span class="sc">$</span>tree, fechas36)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mt_ml_rtt, <span class="at">align.tip.label =</span> <span class="cn">TRUE</span>)</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nodelabels</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="guion9_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Como suele suceder, la raíz (en los árboles enraizados) es el nodo que sigue a las hojas, es decir el 37, porque los 36 primeros números son las puntas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>fechasNodos <span class="ot">&lt;-</span> <span class="fu">c</span>(fechas36, <span class="sc">-</span><span class="dv">6500000</span>, <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">34</span>))</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>fechasEstimadas <span class="ot">&lt;-</span> <span class="fu">estimate.dates</span>(mt_ml_rtt, fechasNodos)</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>tasaEstimada <span class="ot">&lt;-</span> <span class="fu">estimate.mu</span>(mt_ml_rtt, fechasNodos)</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Creamos una copia del árbol...</span></span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>mt_ml_años <span class="ot">&lt;-</span> mt_ml_rtt</span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a><span class="co"># ...y actualizamos las longitudes de sus ramas como la resta</span></span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a><span class="co"># entre las fechas de los nodos que conectan:</span></span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a>mt_ml_años<span class="sc">$</span>edge.length <span class="ot">&lt;-</span> fechasEstimadas[mt_ml_años<span class="sc">$</span>edge[,<span class="dv">2</span>]] <span class="sc">-</span></span>
<span id="cb88-9"><a href="#cb88-9" aria-hidden="true" tabindex="-1"></a>                          fechasEstimadas[mt_ml_años<span class="sc">$</span>edge[,<span class="dv">1</span>]]</span>
<span id="cb88-10"><a href="#cb88-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mt_ml_años)</span>
<span id="cb88-11"><a href="#cb88-11" aria-hidden="true" tabindex="-1"></a><span class="fu">axisPhylo</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="guion9_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>tasaEstimada</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.314216e-08</code></pre>
</div>
</div>
<p>Al forzar que la raíz esté a unos 6.5 millones de años, la tasa de mutación estimada disminuye. Es habitual que las tasas parezcan diferentes a diferentes profundidades del árbol, o entre linajes diferentes.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>